{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.1678.0 (24.12)+2a034ab280bddf891eb7bb9ebfe6996f9c3a3196"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Saldo\",\"Movimientos\",\"Productos\",\"Tipo Movimiento\",\"Path\",\"Medidas Movimientos\",\"Especie\",\"Años\",\"Meses\",\"Meses con Datos\",\"Pagos Especie - Origen\",\"Cobros Especie - Origen\",\"Tipo Pago Especie\",\"Tipo Cobro Especie\",\"Pagos Especie\",\"Cobros Especie\",\"Movimientos Origen\",\"Transacciones\",\"Transacciones Agrupadas\",\"Dividendos\",\"Medidas Transacciones\",\"Medidas Saldo\",\"IRPF Ahorro\",\"Medidas IRPF\",\"CalcularFIFO\",\"ConsumoFIFO\",\"Pruebas\",\"Path (Prod)\",\"Path (Test)\",\"Path (Dev)\",\"Origen Data File\",\"Test Data\",\"Transacciones Power Query\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"DevMode\",\"CalcGroup\"]"
      }
    ],
    "culture": "es-ES",
    "cultures": [
      {
        "name": "es-ES",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "Path",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "expression": "\"https://github.com/imoremu/financeBI/raw/refs/heads/imoremu/issue6/data/dev/data.xlsx\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a2aa19e7-94ab-40b4-b77d-780b67c32947"
      },
      {
        "name": "Especie",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = #\"Origen Data File\",",
          "    #\"Filas filtradas1\" = Table.SelectRows(Origen, each ([Name] = \"T_Pagos_Especie\")),",
          "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Filas filtradas1\",{\"Data\"}),",
          "    #\"Se expandió Data\" = Table.ExpandTableColumn(#\"Otras columnas quitadas\", \"Data\", {\"Concepto\", \"Año\", \"Mes\", \"CLASIFICACION COBRO\", \"CLASIFICACION PAGO\", \"IMPORTE (€)\"}, {\"Concepto\", \"Año / Concepto\", \"Mes / Concepto\", \"CLASIFICACION COBRO\", \"CLASIFICACION PAGO\", \"IMPORTE (€)\"}),",
          "    #\"Consultas combinadas\" = Table.NestedJoin(#\"Se expandió Data\", {\"Año / Concepto\"}, Años, {\"*\"}, \"Años\", JoinKind.LeftOuter),",
          "    #\"Se expandió Años\" = Table.ExpandTableColumn(#\"Consultas combinadas\", \"Años\", {\"FECHA\"}, {\"Años.FECHA\"}),",
          "    #\"Agregar columna personalizada\" = Table.AddColumn(#\"Se expandió Años\", \"Año\", each if [Años.FECHA]= null then [#\"Año / Concepto\"] else [Años.FECHA], type text),",
          "    #\"Consultas combinadas1\" = Table.NestedJoin(#\"Agregar columna personalizada\", {\"Año\", \"Mes / Concepto\"}, Meses, {\"Año\", \"*\"}, \"Meses\", JoinKind.LeftOuter),",
          "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Consultas combinadas1\",{{\"Mes / Concepto\", type text}}),",
          "    #\"Se expandió Meses\" = Table.ExpandTableColumn(#\"Tipo cambiado\", \"Meses\", {\"Mes\"}, {\"Meses.Mes\"}),",
          "    #\"[Columna] Meses]\" = Table.AddColumn(#\"Se expandió Meses\", \"Mes\", each if [Meses.Mes]= null then [#\"Mes / Concepto\"] else [Meses.Mes], type text),",
          "    #\"Otras columnas quitadas1\" = Table.SelectColumns(#\"[Columna] Meses]\",{\"IMPORTE (€)\", \"Año\", \"Mes\", \"CLASIFICACION COBRO\", \"CLASIFICACION PAGO\", \"Concepto\"}),",
          "    #\"Personalizada agregada\" = Table.AddColumn(#\"Otras columnas quitadas1\", \"CATEGORÍA\", each \"Especie\"),",
          "    #\"Consultas combinadas2\" = Table.NestedJoin(#\"Personalizada agregada\", {\"Mes\", \"Año\"}, Meses, {\"Mes\", \"Año\"}, \"Meses\", JoinKind.Inner),",
          "    #\"Se expandió Meses1\" = Table.ExpandTableColumn(#\"Consultas combinadas2\", \"Meses\", {\"Índice\"}, {\"Meses.Índice\"}),",
          "    #\"Columna combinada insertada\" = Table.AddColumn(#\"Se expandió Meses1\", \"FECHA\", each Text.Combine({\"1/\", Text.From([Meses.Índice], \"es-ES\"), \"/\", Text.From([Año], \"es-ES\")}), type text),",
          "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Columna combinada insertada\",{{\"FECHA\", type date}})",
          "in",
          "    #\"Tipo cambiado1\""
        ],
        "kind": "m",
        "lineageTag": "6df10bda-7c31-4f86-8cfa-cf0faa72dbfa",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Años",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = #\"Movimientos Origen\",",
          "    #\"Otras columnas quitadas\" = Table.SelectColumns(Origen,{\"FECHA\"}),",
          "    #\"Año extraído\" = Table.TransformColumns(#\"Otras columnas quitadas\",{{\"FECHA\", Date.Year, Int64.Type}}),",
          "    #\"Duplicados quitados\" = Table.Distinct(#\"Año extraído\"),",
          "    #\"Personalizada agregada\" = Table.AddColumn(#\"Duplicados quitados\", \"Personalizado\", each \"*\"),",
          "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Personalizada agregada\",{{\"Personalizado\", \"*\"}})",
          "in",
          "    #\"Columnas con nombre cambiado\""
        ],
        "kind": "m",
        "lineageTag": "b608a801-da5d-4734-af75-03e171a22723",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Meses",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs1LLcpXitWJVnJLTSqCsX0Ti6ogLMekoswcqFglRMirNC8TxsqBshzT84tLIMzg1IKSzNRcoGFgrn9ySSmM7ZdfhiTjkpkM48UCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Mes = _t]),",
          "    #\"Índice agregado\" = Table.AddIndexColumn(Origen, \"Índice\", 1, 1, Int64.Type),",
          "    #\"Personalizada agregada\" = Table.AddColumn(#\"Índice agregado\", \"*\", each \"*\"),",
          "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Personalizada agregada\",{{\"Mes\", type text}}),",
          "    #\"Consultas combinadas\" = Table.NestedJoin(#\"Tipo cambiado\", {\"*\"}, Años, {\"*\"}, \"Años\", JoinKind.LeftOuter),",
          "    #\"Se expandió Años\" = Table.ExpandTableColumn(#\"Consultas combinadas\", \"Años\", {\"FECHA\"}, {\"Año\"}),",
          "    #\"Consultas combinadas1\" = Table.NestedJoin(#\"Se expandió Años\", {\"Índice\", \"Año\"}, #\"Meses con Datos\", {\"Mes\", \"Año\"}, \"Meses con Datos\", JoinKind.RightOuter),",
          "    #\"Se expandió Meses con Datos\" = Table.ExpandTableColumn(#\"Consultas combinadas1\", \"Meses con Datos\", {\"Mes\", \"Año\"}, {\"Meses con Datos.Mes\", \"Meses con Datos.Año\"}),",
          "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Se expandió Meses con Datos\",{\"Mes\", \"Índice\", \"*\", \"Año\"}),",
          "    #\"Columna combinada insertada\" = Table.AddColumn(#\"Otras columnas quitadas\", \"FECHA\", each Text.Combine({\"01/\", Text.From([Índice], \"es-ES\"), \"/\", Text.From([Año], \"es-ES\")}), type text),",
          "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Columna combinada insertada\",{{\"FECHA\", type date}}),",
          "    #\"Filas ordenadas\" = Table.Sort(#\"Tipo cambiado1\",{{\"Año\", Order.Ascending}})",
          "in",
          "    #\"Filas ordenadas\""
        ],
        "kind": "m",
        "lineageTag": "bcb08a50-39a7-4e62-8cdd-7ea8d37bb2ae",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Meses con Datos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = #\"Movimientos Origen\",",
          "    #\"Otras columnas quitadas\" = Table.SelectColumns(Origen,{\"FECHA\"}),",
          "    #\"Mes insertado\" = Table.AddColumn(#\"Otras columnas quitadas\", \"Mes\", each Date.Month([FECHA]), Int64.Type),",
          "    #\"Año insertado\" = Table.AddColumn(#\"Mes insertado\", \"Año\", each Date.Year([FECHA]), Int64.Type),",
          "    #\"Filas ordenadas1\" = Table.Sort(#\"Año insertado\",{{\"Año\", Order.Ascending}}),",
          "    #\"Columnas quitadas1\" = Table.RemoveColumns(#\"Filas ordenadas1\",{\"FECHA\"}),",
          "    #\"Duplicados quitados\" = Table.Distinct(#\"Columnas quitadas1\"),",
          "    #\"Filas ordenadas\" = Table.Sort(#\"Duplicados quitados\",{{\"Año\", Order.Ascending}})",
          "in",
          "    #\"Filas ordenadas\""
        ],
        "kind": "m",
        "lineageTag": "55f7a003-e362-4407-93a1-840c3d1b305b",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Pagos Especie - Origen",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = Especie,",
          "    #\"Columnas quitadas\" = Table.RemoveColumns(Origen,{\"CLASIFICACION COBRO\"}),",
          "    #\"[Columna] Cantidad\" = Table.AddColumn(#\"Columnas quitadas\", \"Cantidad (€)\", each [#\"IMPORTE (€)\"], type number),",
          "    #\"Valor reemplazado\" = Table.ReplaceValue(#\"[Columna] Cantidad\",each [#\"IMPORTE (€)\"], each [#\"IMPORTE (€)\"] * -1,Replacer.ReplaceValue,{\"IMPORTE (€)\"}),",
          "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Valor reemplazado\",{{\"CLASIFICACION PAGO\", \"CLASIFICACIÓN\"}})",
          "in",
          "    #\"Columnas con nombre cambiado\""
        ],
        "kind": "m",
        "lineageTag": "ba794d35-a267-47a1-bbed-6997ebcfb890",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Cobros Especie - Origen",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = Especie,",
          "    #\"Columnas quitadas\" = Table.RemoveColumns(Origen,{\"CLASIFICACION PAGO\"}),",
          "    #\"Columna duplicada\" = Table.AddColumn(#\"Columnas quitadas\", \"Cantidad (€)\", each [#\"IMPORTE (€)\"], type any),",
          "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Columna duplicada\",{{\"CLASIFICACION COBRO\", \"CLASIFICACIÓN\"}}),",
          "    #\"Filas ordenadas\" = Table.Sort(#\"Columnas con nombre cambiado\",{{\"Año\", Order.Ascending}})",
          "in",
          "    #\"Filas ordenadas\""
        ],
        "kind": "m",
        "lineageTag": "4172a8a8-adb9-4f9e-ace5-82abb153fe48",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Tipo Pago Especie",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = #\"Pagos Especie - Origen\",",
          "    #\"Otras columnas quitadas\" = Table.SelectColumns(Origen,{\"CLASIFICACIÓN\", \"CATEGORÍA\"}),",
          "    #\"Duplicados quitados\" = Table.Distinct(#\"Otras columnas quitadas\"),",
          "    #\"Columna duplicada\" = Table.DuplicateColumn(#\"Duplicados quitados\", \"CATEGORÍA\", \"SUBCATEGORÍA\"),",
          "    #\"Columna duplicada1\" = Table.DuplicateColumn(#\"Columna duplicada\", \"SUBCATEGORÍA\", \"DESCRIPCIÓN\"),",
          "    #\"Personalizada agregada1\" = Table.AddColumn(#\"Columna duplicada1\", \"TIPO\", each \"Gasto\")",
          "in",
          "    #\"Personalizada agregada1\""
        ],
        "kind": "m",
        "lineageTag": "ee3edbea-59a5-438e-84ce-dc06896643b6",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Tipo Cobro Especie",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = #\"Cobros Especie - Origen\",",
          "    #\"Otras columnas quitadas\" = Table.SelectColumns(Origen,{\"CLASIFICACIÓN\", \"CATEGORÍA\"}),",
          "    #\"Duplicados quitados\" = Table.Distinct(#\"Otras columnas quitadas\"),",
          "    #\"Columna duplicada\" = Table.DuplicateColumn(#\"Duplicados quitados\", \"CATEGORÍA\", \"SUBCATEGORÍA\"),",
          "    #\"Columna duplicada1\" = Table.DuplicateColumn(#\"Columna duplicada\", \"SUBCATEGORÍA\", \"DESCRIPCIÓN\"),",
          "    #\"Personalizada agregada1\" = Table.AddColumn(#\"Columna duplicada1\", \"TIPO\", each \"Ingreso\")",
          "in",
          "    #\"Personalizada agregada1\""
        ],
        "kind": "m",
        "lineageTag": "96992fc9-0882-4bef-9aca-518d20b4a236",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Pagos Especie",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = #\"Pagos Especie - Origen\",",
          "    #\"Consultas combinadas\" = Table.NestedJoin(Origen, {\"CLASIFICACIÓN\", \"CATEGORÍA\"}, #\"Tipo Movimiento\", {\"CLASIFICACIÓN\", \"CATEGORÍA\"}, \"Tipo Movimiento\", JoinKind.LeftOuter),",
          "    #\"Se expandió Tipo Movimiento\" = Table.ExpandTableColumn(#\"Consultas combinadas\", \"Tipo Movimiento\", {\"Índice\"}, {\"Tipo Movimiento.Índice\"}),",
          "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Se expandió Tipo Movimiento\",{\"IMPORTE (€)\", \"Cantidad (€)\", \"Tipo Movimiento.Índice\", \"FECHA\"}),",
          "    #\"Columnas reordenadas\" = Table.ReorderColumns(#\"Otras columnas quitadas\",{\"FECHA\", \"IMPORTE (€)\", \"Cantidad (€)\", \"Tipo Movimiento.Índice\"}),",
          "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Columnas reordenadas\",{{\"IMPORTE (€)\", Currency.Type}, {\"Cantidad (€)\", Currency.Type}})",
          "in",
          "    #\"Tipo cambiado\""
        ],
        "kind": "m",
        "lineageTag": "68238d80-9f94-44d8-96ab-5b669201d1a8",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Cobros Especie",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = #\"Cobros Especie - Origen\",",
          "    #\"Consultas combinadas\" = Table.NestedJoin(Origen, {\"CLASIFICACIÓN\", \"CATEGORÍA\"}, #\"Tipo Movimiento\", {\"CLASIFICACIÓN\", \"CATEGORÍA\"}, \"Tipo Movimiento\", JoinKind.LeftOuter),",
          "    #\"Se expandió Tipo Movimiento\" = Table.ExpandTableColumn(#\"Consultas combinadas\", \"Tipo Movimiento\", {\"Índice\"}, {\"Tipo Movimiento.Índice\"}),",
          "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Se expandió Tipo Movimiento\",{\"IMPORTE (€)\", \"Cantidad (€)\", \"Tipo Movimiento.Índice\", \"FECHA\"}),",
          "    #\"Columnas reordenadas\" = Table.ReorderColumns(#\"Otras columnas quitadas\",{\"FECHA\", \"IMPORTE (€)\", \"Cantidad (€)\", \"Tipo Movimiento.Índice\"}),",
          "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Columnas reordenadas\",{{\"IMPORTE (€)\", Currency.Type}, {\"Cantidad (€)\", Currency.Type}})",
          "in",
          "    #\"Tipo cambiado\""
        ],
        "kind": "m",
        "lineageTag": "99f11e60-4bff-4cbb-b8f6-501d7955d0b6",
        "queryGroup": "Movimientos"
      },
      {
        "name": "Movimientos Origen",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = #\"Origen Data File\",",
          "    T_Movimientos_Table = Origen{[Item=\"T_Movimientos\",Kind=\"Table\"]}[Data],",
          "    #\"[Column][Add] Test\" = if Table.HasColumns(T_Movimientos_Table, \"Test\") then T_Movimientos_Table else Table.AddColumn(T_Movimientos_Table, \"Test\", each \"Producción\")",
          "in",
          "    #\"[Column][Add] Test\""
        ],
        "kind": "m",
        "lineageTag": "d278a3d9-9f0c-400a-933c-08efa0a36b69",
        "queryGroup": "Movimientos"
      },
      {
        "name": "CalcularFIFO",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(acumulador as record, ticker as text, cantVenta as number, precioVenta as number) as record =>",
          "let",
          "    // Obtener el stock actual para el ticker, o una lista vacía si no existe",
          "    stockTickerAnterior = Record.FieldOrDefault(acumulador[Stock], ticker, {}),",
          "    ",
          "    // Consumir el stock según FIFO",
          "    consumoRealizado = ConsumoFIFO(stockTickerAnterior, cantVenta),",
          "    nuevoStockTicker = consumoRealizado[StockRestante],",
          "",
          "    // Actualizar el stock en el acumulador",
          "    // Aquí reemplazamos o añadimos el ticker utilizando Record.Combine",
          "    nuevoStock = Record.Combine({ ",
          "        acumulador[Stock], ",
          "        Record.FromList({ nuevoStockTicker }, { ticker }) ",
          "    }),",
          "",
          "    // Calcular el costo total de la venta y la ganancia",
          "    costoTotalVenta  = consumoRealizado[CostoAcumulado],",
          "    gananciaVenta    = (precioVenta * cantVenta) - costoTotalVenta,",
          "    gananciaAcumulada= acumulador[Ganancia] + gananciaVenta",
          "in",
          "    [",
          "        Stock    = nuevoStock, ",
          "        Ganancia = gananciaAcumulada",
          "    ]"
        ],
        "kind": "m",
        "lineageTag": "b9870c52-bffc-40ad-be25-a10da4a5e187",
        "queryGroup": "IRPF"
      },
      {
        "name": "ConsumoFIFO",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Origen = (listaStock as list, cantidadRestante as number) as record =>",
          "        if cantidadRestante = 0 or List.IsEmpty(listaStock) then",
          "            [ StockRestante = listaStock, CostoAcumulado = 0 ]",
          "        else",
          "            let",
          "                primerLote = List.First(listaStock),",
          "                loteCantidad = primerLote[Cantidad],",
          "                lotePrecio   = primerLote[Precio],",
          "                resultado =",
          "                    if loteCantidad <= cantidadRestante then",
          "                        let",
          "                            // Consumir todo el lote y continuar",
          "                            siguiente         = @ConsumoFIFO(List.Skip(listaStock, 1), cantidadRestante - loteCantidad),",
          "                            costoLote         = loteCantidad * lotePrecio,",
          "                            costoAcumulado    = costoLote + siguiente[CostoAcumulado]",
          "                        in",
          "                            [ ",
          "                                StockRestante   = siguiente[StockRestante],",
          "                                CostoAcumulado = costoAcumulado",
          "                            ]",
          "                    else",
          "                        let",
          "                            // Consumir parte del lote y actualizar el lote",
          "                            nuevoPrimerLote   = [ Cantidad = loteCantidad - cantidadRestante, Precio = lotePrecio ],",
          "                            costoParcial      = cantidadRestante * lotePrecio,",
          "                            stockRestante     = List.Combine({ { nuevoPrimerLote }, List.Skip(listaStock, 1) })",
          "                        in",
          "                            [ ",
          "                                StockRestante   = stockRestante,",
          "                                CostoAcumulado = costoParcial",
          "                            ]",
          "            in",
          "                resultado",
          "in",
          "    Origen"
        ],
        "kind": "m",
        "lineageTag": "353c8b9e-bc7a-41c4-b99c-0e09b803869c",
        "queryGroup": "IRPF"
      },
      {
        "name": "Pruebas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "// Suponiendo que tienes una tabla llamada Transacciones",
          "let",
          "    // Paso 1: Definir la tabla de transacciones",
          "    Transacciones = Table.FromRecords({",
          "        [Acción=\"DE\", Tipo=\"Compra\", Cantidad=1000, Precio=100],",
          "        [Acción=\"DE\", Tipo=\"Compra\", Cantidad=500, Precio=125],",
          "        [Acción=\"DE\", Tipo=\"Venta\", Cantidad=750, Precio=150],",
          "        [Acción=\"DE\", Tipo=\"Compra\", Cantidad=400, Precio=140],",
          "        [Acción=\"DE\", Tipo=\"Venta\", Cantidad=1000, Precio=200],",
          "        [Acción=\"AAPL\", Tipo=\"Compra\", Cantidad=300, Precio=250],",
          "        [Acción=\"AAPL\", Tipo=\"Venta\", Cantidad=150, Precio=300]",
          "    }),",
          "    #\"Multiplicación insertada\" = Table.AddColumn(Transacciones, \"Multiplicación\", each [Cantidad] * [Precio], type number),",
          "    ",
          "    // Paso 2: Agregar una columna de índice para mantener el orden",
          "    TransaccionesConIndice = Table.AddIndexColumn(#\"Multiplicación insertada\", \"Índice\", 1, 1, Int64.Type),",
          "    ",
          "    // Paso 3: Definir la función CalcularFIFO",
          "    CalcularFIFO = (acumulador as record, ticker as text, cantVenta as number, precioVenta as number) as record =>",
          "    let",
          "        // Obtener el stock actual para el ticker, o una lista vacía si no existe",
          "        stockTickerAnterior = Record.FieldOrDefault(acumulador[Stock], ticker, {}),",
          "        ",
          "        // Función recursiva para consumir el stock según FIFO",
          "        ConsumoFIFO = (listaStock as list, cantidadRestante as number) as record =>",
          "            if cantidadRestante = 0 or List.IsEmpty(listaStock) then",
          "                [ StockRestante = listaStock, CostoAcumulado = 0 ]",
          "            else",
          "                let",
          "                    primerLote = List.First(listaStock),",
          "                    loteCantidad = primerLote[Cantidad],",
          "                    lotePrecio   = primerLote[Precio],",
          "                    resultado =",
          "                        if loteCantidad <= cantidadRestante then",
          "                            let",
          "                                siguiente         = @ConsumoFIFO(List.Skip(listaStock, 1), cantidadRestante - loteCantidad),",
          "                                costoLote         = loteCantidad * lotePrecio,",
          "                                costoAcumulado    = costoLote + siguiente[CostoAcumulado]",
          "                            in",
          "                                [ ",
          "                                    StockRestante   = siguiente[StockRestante],",
          "                                    CostoAcumulado = costoAcumulado",
          "                                ]",
          "                        else",
          "                            let",
          "                                nuevoPrimerLote   = [ Cantidad = loteCantidad - cantidadRestante, Precio = lotePrecio ],",
          "                                costoParcial      = cantidadRestante * lotePrecio,",
          "                                stockRestante     = List.Combine({ { nuevoPrimerLote }, List.Skip(listaStock, 1) })",
          "                            in",
          "                                [ ",
          "                                    StockRestante   = stockRestante,",
          "                                    CostoAcumulado = costoParcial",
          "                                ]",
          "                in",
          "                    resultado,",
          "        ",
          "        // Consumir el stock según FIFO",
          "        consumoRealizado = ConsumoFIFO(stockTickerAnterior, cantVenta),",
          "        nuevoStockTicker = consumoRealizado[StockRestante],",
          "        ",
          "        // Actualizar el stock en el acumulador usando Record.Combine",
          "        nuevoStock = Record.Combine({ ",
          "            acumulador[Stock], ",
          "            Record.FromList({ nuevoStockTicker }, { ticker }) ",
          "        }),",
          "        ",
          "        // Calcular el costo total de la venta y la ganancia",
          "        costoTotalVenta  = consumoRealizado[CostoAcumulado],",
          "        gananciaVenta    = (precioVenta * cantVenta) - costoTotalVenta,",
          "        gananciaAcumulada= acumulador[Ganancia] + gananciaVenta",
          "    in",
          "        [",
          "            Stock    = nuevoStock, ",
          "            Ganancia = gananciaAcumulada",
          "        ],",
          "    ",
          "    // Paso 4: Procesar las transacciones con List.Accumulate",
          "    Resultado = List.Accumulate(",
          "        Table.ToRecords(TransaccionesConIndice),",
          "        [ Stock = [], Ganancia = 0, GananciasPorVenta = {} ],",
          "        (acumulador, transaccion) =>",
          "            let",
          "                tipo = transaccion[Tipo],",
          "                ticker = transaccion[Acción],",
          "                cant = transaccion[Cantidad],",
          "                precio = transaccion[Precio],",
          "                // Verificar si es una compra o venta",
          "                nuevoEstado =",
          "                    if tipo = \"Compra\" then",
          "                        // Agregar al stock del ticker correspondiente",
          "                        let",
          "                            stockActual = Record.FieldOrDefault(acumulador[Stock], ticker, {}),",
          "                            nuevoStock = List.Combine({ stockActual, { [ Cantidad = cant, Precio = precio ] } }),",
          "                            // Usar Record.Combine para agregar o actualizar el ticker",
          "                            stockActualizado = Record.Combine({ ",
          "                                acumulador[Stock], ",
          "                                Record.FromList({ nuevoStock }, { ticker }) ",
          "                            }),",
          "                            // No hay ganancia en una compra",
          "                            gananciaPorVenta = List.Combine({ acumulador[GananciasPorVenta], { null } })",
          "                        in",
          "                            [",
          "                                Stock = stockActualizado,",
          "                                Ganancia = acumulador[Ganancia],",
          "                                GananciasPorVenta = gananciaPorVenta",
          "                            ]",
          "                    else",
          "                        // Procesar la venta con FIFO",
          "                        let",
          "                            resultadoFIFO = CalcularFIFO(acumulador, ticker, cant, precio),",
          "                            // Calcular la ganancia de esta venta",
          "                            gananciaActual = resultadoFIFO[Ganancia] - acumulador[Ganancia],",
          "                            // Añadir la ganancia de esta venta a la lista",
          "                            gananciaPorVenta = List.Combine({ acumulador[GananciasPorVenta], { gananciaActual } })",
          "                        in",
          "                            [",
          "                                Stock = resultadoFIFO[Stock],",
          "                                Ganancia = resultadoFIFO[Ganancia],",
          "                                GananciasPorVenta = gananciaPorVenta",
          "                            ]",
          "            in",
          "                nuevoEstado",
          "    ),",
          "    ",
          "    // Paso 5: Añadir la columna de Ganancias a la tabla original",
          "    // Primero, crear una lista de ganancias por fila",
          "    ListaGanancias = Resultado[GananciasPorVenta],",
          "    ",
          "    // Agregar la lista como una nueva columna a la tabla original",
          "    TransaccionesConGanancia = Table.AddColumn(",
          "    TransaccionesConIndice,",
          "    \"Ganancia\",",
          "    each List.Skip(ListaGanancias, [Índice] - 1){0}",
          ")",
          "in",
          "    TransaccionesConGanancia"
        ],
        "kind": "m",
        "lineageTag": "6c27150f-0f49-4ac9-9908-8520cd364d50",
        "queryGroup": "Pruebas"
      },
      {
        "name": "Path (Prod)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://github.com/imoremu/financeBI/raw/refs/heads/main/data/dev/data.xlsx\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "ed311670-0039-42b3-8c51-44f01d93b7f5"
      },
      {
        "name": "Path (Test)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://github.com/imoremu/financeBI/raw/refs/heads/main/data/test/data.xlsx\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "f737d9c4-c6ff-4d17-87cb-57bd2af5ee83"
      },
      {
        "name": "Transacciones Agrupadas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = Transacciones,",
          "    #\"Filas filtradas\" = Table.SelectRows(Origen, each (List.Contains({\"Compra\",\"Venta\"}, [Tipo Transacción]))),",
          "    #\"Filas ordenadas\" = Table.Sort(#\"Filas filtradas\",{{\"ID\", Order.Descending}}),",
          "    Buffer = Table.Buffer(#\"Filas ordenadas\"),",
          "    #\"Otras columnas quitadas\" = Table.SelectColumns(Buffer,{\"Fecha\", \"Producto\", \"Precio Participación\", \"Importe\", \"Participaciones Acumuladas\"}),",
          "    #\"Duplicados quitados\" = Table.Distinct(#\"Otras columnas quitadas\", {\"Fecha\", \"Producto\"}),",
          "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Duplicados quitados\",{{\"Participaciones Acumuladas\", \"Participaciones\"}, {\"Precio Participación\", \"Valor liquidativo\"}}),",
          "    #\"Personalizada agregada\" = Table.AddColumn(#\"Columnas con nombre cambiado\", \"Saldo\", each [Participaciones] * [Valor liquidativo]),",
          "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"Personalizada agregada\",{{\"Saldo\", type number}})",
          "in",
          "    #\"Tipo cambiado\""
        ],
        "kind": "m",
        "lineageTag": "01c2a73d-f2d5-4d85-9e73-4b818a36bdfc",
        "queryGroup": "Saldo"
      },
      {
        "name": "Path (Dev)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"https://github.com/imoremu/financeBI/raw/refs/heads/main/data/dev/data.xlsx\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "729f91fe-dd33-4afe-9afa-c7c19df53d2e"
      },
      {
        "name": "Origen Data File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = if Text.Contains(Path, \"http\") then Excel.Workbook(Web.Contents(Path), null, true) else Excel.Workbook(File.Contents(Path), null, true)",
          "in",
          "    Origen"
        ],
        "kind": "m",
        "lineageTag": "d912bd64-0484-42bd-be55-fe72a89c8d06"
      },
      {
        "name": "Transacciones Power Query",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Origen = #\"Origen Data File\",",
          "    T_Saldo_Table = Origen{[Item=\"T_Transacciones\",Kind=\"Table\"]}[Data],",
          "    #\"[Column][Add] Test\" = if Table.HasColumns(T_Saldo_Table, \"Test\") then T_Saldo_Table else Table.AddColumn(T_Saldo_Table, \"Test\", each \"Producción\"),",
          "    #\"Columnas con nombre cambiado1\" = Table.RenameColumns(#\"[Column][Add] Test\",{{\"Importe Bruto\", \"Importe\"}}),",
          "    #\"[Tipos][Update]\" = Table.TransformColumnTypes(#\"Columnas con nombre cambiado1\",{{\"Producto\", type text}, {\"Participaciones\", Currency.Type}, {\"Precio Participación\", Currency.Type}, {\"Importe\", Currency.Type}, {\"Fecha\", type date}, {\"Comisión\", Currency.Type}, {\"Retenido\", Currency.Type}, {\"Cuenta Producto\", type text}, {\"Año IRPF\", Int64.Type}, {\"Tipo Transacción\", type text}, {\"Producto Contraparte\", type text}, {\"Cuenta Contraparte\", type text}, {\"Precio (Moneda Transacción)\", Currency.Type}, {\"Cambio\", Currency.Type}, {\"Importe Bruto (Moneda Transacción)\", Currency.Type}, {\"Retenido (Moneda Transacción)\", Currency.Type}, {\"Comisión (Moneda Transacción)\", Currency.Type}, {\"Detalle\", type text}, {\"Hora\", type time}, {\"Test\", type text}}),",
          "    #\"[Column][Add] Fecha/Hora\" = Table.AddColumn(#\"[Tipos][Update]\", \"Fecha/Hora\", each Date.ToText([Fecha], \"yyyy-MM-dd\") & \" \" & Time.ToText(if [Hora] = null then #time(0,0,0) else [Hora], \"HH:mm:ss\")),",
          "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"[Column][Add] Fecha/Hora\",{{\"Fecha/Hora\", type datetime}}),",
          "    #\"Transaccion Espejo\" = Table.RenameColumns(",
          "        #\"Tipo cambiado\",",
          "        {",
          "            {\"Producto\", \"Producto Contraparte\"},  // Renombramos \"Producto\" temporalmente",
          "            {\"Producto Contraparte\", \"Producto\"},  // Renombramos \"Producto Contraparte\" a \"Producto\"",
          "            {\"Cuenta Producto\", \"Cuenta Contraparte\"},  // Renombramos \"Cuenta Producto\" temporalmente",
          "            {\"Cuenta Contraparte\", \"Cuenta Producto\"}  // Renombramos \"Cuenta Contraparte\" a \"Cuenta Producto\"",
          "        }),",
          "    #\"[Update] Importe Con comisión\" = Table.AddColumn(#\"Transaccion Espejo\", \"Importe Con Comisión\", each [Importe] + [Comisión]),",
          "    #\"[Update] Eliminado Importe Antiguo\" = Table.RemoveColumns(#\"[Update] Importe Con comisión\",{\"Importe\"}),",
          "    #\"[Update] Importe Nuevo\" = Table.RenameColumns(#\"[Update] Eliminado Importe Antiguo\",{{\"Importe Con Comisión\", \"Importe\"}}),",
          "    #\"[Filtro] Eliminar dividendos de Espejo\" = Table.SelectRows(#\"[Update] Importe Nuevo\", each ([Tipo Transacción] <> \"Dividendos\")),",
          "    ",
          "    #\"[Limpiar] Transacción Espejo\" = Table.TransformColumns(",
          "    #\"[Filtro] Eliminar dividendos de Espejo\",",
          "    {",
          "        {\"Tipo Transacción\", each if _ = \"Compra\" then \"Venta\" else \"Compra\"},  // Invertir Compra/Venta,",
          "        {\"Importe\", each _ * -1},",
          "        {\"Participaciones\", each null},  ",
          "        {\"Precio Participación\", each null}, ",
          "        {\"Precio (Moneda Transacción)\", each null},  ",
          "        {\"Retenido\", each null},",
          "        {\"Retenido (Moneda Transacción)\", each null},",
          "        {\"Año IRPF\", each null},",
          "        {\"Comisión\", each null},",
          "        {\"Comisión (Moneda Transacción)\", each null}",
          "    }",
          "),",
          "    #\"[Anexion] Espejo\" = Table.Combine({#\"Tipo cambiado\", #\"[Limpiar] Transacción Espejo\"}),",
          "    #\"Duplicados quitados\" = Table.Distinct(#\"[Anexion] Espejo\", {\"Producto\", \"Fecha\", \"Hora\", \"Producto Contraparte\", \"Importe\"}),",
          "    #\"[Update] Comision - Null to 0\" = Table.ReplaceValue(#\"Duplicados quitados\",null,0,Replacer.ReplaceValue,{\"Comisión\"}),",
          "    #\"[Columna][Add] Total\" = Table.AddColumn(#\"[Update] Comision - Null to 0\", \"Total Bruto\", each [Importe] + [Comisión], type number),",
          "    #\"[Columna][Add] Año IRPF Fijado\" = Table.AddColumn(#\"[Columna][Add] Total\", \"Año IRPF Fijado\", each if [Año IRPF] = null then false else true, type logical),",
          "    #\"[Modify] Año IRPF\" = Table.ReplaceValue(#\"[Columna][Add] Año IRPF Fijado\",null, each if [Tipo Transacción] = \"Compra\" then null else List.Max({Date.Year([Fecha]), Date.Year(DateTime.LocalNow()) - 1}),Replacer.ReplaceValue,{\"Año IRPF\"}),",
          "    #\"[Tipo] Año a Integer\" = Table.TransformColumnTypes(#\"[Modify] Año IRPF\",{{\"Año IRPF\", Int64.Type}}),",
          "    #\"Filas ordenadas\" = Table.Sort(#\"[Tipo] Año a Integer\",{{\"Producto\", Order.Ascending},{\"Fecha\", Order.Ascending}}),",
          "    Buffer = Table.Buffer(#\"Filas ordenadas\"),",
          "    #\"Índice agregado\" = Table.AddIndexColumn(Buffer, \"ID\", 1, 1, Int64.Type),",
          "    ListaRegistros = Table.ToRecords(#\"Índice agregado\"),",
          "    ListaAcumulada =",
          "        List.Accumulate(",
          "            ListaRegistros,",
          "            // Estado inicial",
          "            [",
          "                ParticipacionesAcum = 0,",
          "                PrecioMedio = 0,",
          "                ProductoActual = \"\",",
          "                RegistrosResultado = {}",
          "            ],",
          "            // Función de acumulación",
          "            (estadoAnterior, registroActual) =>",
          "            let                ",
          "                tipo = registroActual[Tipo Transacción],",
          "                anteriorProducto = estadoAnterior[ProductoActual],",
          "                actualProducto = registroActual[Producto],",
          "                anteriorPart = if actualProducto <> anteriorProducto then 0 else estadoAnterior[ParticipacionesAcum],",
          "                actualPart = registroActual[Participaciones],",
          "                anteriorPrecio = if actualProducto <> anteriorProducto then 0 else estadoAnterior[PrecioMedio],                ",
          "                actualCoste = registroActual[Total Bruto],",
          "                ",
          "                ",
          "                // Calculamos los nuevos valores según la transacción actual",
          "                nuevasPart = if List.Contains({\"Compra\", \"Venta\"},tipo) then anteriorPart + registroActual[Participaciones] else anteriorPart,",
          "                nuevoPrecioMedio = if tipo = \"Compra\" then ((anteriorPart * anteriorPrecio) + actualCoste) / nuevasPart else anteriorPrecio,                ",
          "",
          "                // Generamos un registro que incluye datos originales y los acumulados",
          "                registroExtendido = Record.Combine(",
          "                    {",
          "                        registroActual,",
          "                        [",
          "                            ParticipacionesAcum = nuevasPart,",
          "                            PrecioMedio = nuevoPrecioMedio                     ",
          "                        ]",
          "                    }",
          "                ),",
          "                // Anexamos ese registro al historial",
          "                estadoSiguiente = [",
          "                    ParticipacionesAcum = nuevasPart,",
          "                    PrecioMedio = nuevoPrecioMedio,",
          "                    ProductoActual = actualProducto,",
          "                    RegistrosResultado = estadoAnterior[RegistrosResultado] & { registroExtendido }",
          "                ]",
          "            in",
          "                estadoSiguiente",
          "        ),",
          "",
          "    // Extraer la lista final de registros \"extendidos\"",
          "    ResultadoRegistros = ListaAcumulada[RegistrosResultado],",
          "",
          "    // Convertir de nuevo a tabla",
          "    TablaResultado = Table.FromRecords(ResultadoRegistros),",
          "    #\"[Tipos][Update] Refresh\" = Table.TransformColumnTypes(TablaResultado,{{\"Fecha\", type date}, {\"Producto\", type text}, {\"Cuenta Producto\", type text}, {\"Tipo Transacción\", type text}, {\"Participaciones\", Currency.Type}, {\"Precio Participación\", Currency.Type}, {\"Total Bruto\", type number}, {\"Retenido\", Currency.Type}, {\"Año IRPF\", Int64.Type}, {\"Comisión\", Currency.Type}, {\"Año IRPF Fijado\", type logical}, {\"ParticipacionesAcum\", type number}, {\"PrecioMedio\", type number}, {\"Importe\", Currency.Type}, {\"Producto Contraparte\", type text}, {\"Cuenta Contraparte\", type text}, {\"ID\", Int64.Type}, {\"Comisión (Moneda Transacción)\", Currency.Type}, {\"Retenido (Moneda Transacción)\", Currency.Type}, {\"Importe Bruto (Moneda Transacción)\", Currency.Type}, {\"Cambio\", Currency.Type}, {\"Precio (Moneda Transacción)\", Currency.Type}, {\"Hora\", type time}, {\"Test\", type text}, {\"Fecha/Hora\", type datetime}}),",
          "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"[Tipos][Update] Refresh\",{{\"ParticipacionesAcum\", \"Participaciones Acumuladas\"}, {\"PrecioMedio\", \"Precio Medio Hasta Transacción\"}}),",
          "    #\"[Columna][Add] Renta Obtenida\" = Table.AddColumn(#\"Columnas con nombre cambiado\", \"Renta Bruta Obtenida\", each if List.Contains({\"Compra\",\"Venta\"},[Tipo Transacción]) then -1*[Total Bruto] else [Total Bruto], type number)",
          "in",
          "    #\"[Columna][Add] Renta Obtenida\""
        ],
        "kind": "m",
        "lineageTag": "25d977a7-b997-48ee-9509-628ffded1735",
        "queryGroup": "Saldo"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Movimientos"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "IRPF"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Pruebas"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Saldo"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Test"
      }
    ],
    "relationships": [
      {
        "name": "43cb011e-558b-47f0-9437-adf3927ad25b",
        "fromColumn": "Tipo Movimiento.Índice",
        "fromTable": "Movimientos",
        "toColumn": "Índice",
        "toTable": "Tipo Movimiento"
      },
      {
        "name": "7f0b6ed7-6a4b-c5e4-b97a-499fa78154f9",
        "fromColumn": "Año",
        "fromTable": "IRPF Ahorro",
        "toColumn": "Año",
        "toTable": "Años Fiscales"
      },
      {
        "name": "5ea138a3-4eca-421f-b231-372cbcc43b8c",
        "fromColumn": "FECHA",
        "fromTable": "Movimientos",
        "toColumn": "Date",
        "toTable": "Calendario"
      },
      {
        "name": "17e9edd7-2f4c-4d95-9346-ab191afffb83",
        "fromColumn": "Fecha",
        "fromTable": "Saldo",
        "toColumn": "Date",
        "toTable": "Calendario"
      },
      {
        "name": "fbd5c639-342a-f7f8-321b-62d1747fec1f",
        "fromColumn": "Fecha",
        "fromTable": "Dividendos",
        "toColumn": "Date",
        "toTable": "Calendario"
      },
      {
        "name": "8b1bea61-c3f9-0a27-31de-98cd17d27c45",
        "fromColumn": "Fecha",
        "fromTable": "Transacciones",
        "toColumn": "Date",
        "toTable": "Calendario"
      },
      {
        "name": "AutoDetected_6e000d00-7949-4a1a-98fb-3101deab90de",
        "fromColumn": "Producto",
        "fromTable": "Saldo",
        "toColumn": "Producto",
        "toTable": "Productos"
      },
      {
        "name": "e5578d68-57f5-01e9-2a47-7c5e44960af6",
        "fromColumn": "Producto",
        "fromTable": "Transacciones",
        "toColumn": "Producto",
        "toTable": "Productos"
      },
      {
        "name": "0941d729-79d1-b7f7-12c5-0475db64212d",
        "fromColumn": "Producto",
        "fromTable": "Dividendos",
        "toColumn": "Producto",
        "toTable": "Productos"
      },
      {
        "name": "662e5346-ea3b-adcf-c4b6-4224b36bad1f",
        "fromColumn": "Año IRPF",
        "fromTable": "Transacciones",
        "toColumn": "Año",
        "toTable": "Años Fiscales"
      },
      {
        "name": "b40c6ee6-4ff4-4108-9c87-8c3405be1394",
        "fromColumn": "Fecha/Hora",
        "fromTable": "Transacciones",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_93f1543f-944f-4988-9370-48e3eab51efc"
      },
      {
        "name": "3a5f943a-4678-40ea-b351-5487beb493ac",
        "fromColumn": "Fecha/Hora",
        "fromTable": "Dividendos",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b9da2914-fd53-4f32-b21c-39fa4c9bbfb1"
      },
      {
        "name": "5f187c92-9b98-1831-b8c9-73f0037614e4",
        "fromColumn": "Test",
        "fromTable": "Movimientos",
        "toCardinality": "many",
        "toColumn": "Prueba",
        "toTable": "Test Data"
      },
      {
        "name": "dad5e620-7aaf-ee6b-29cf-bbb87a57bb0e",
        "fromColumn": "Test",
        "fromTable": "Transacciones",
        "toCardinality": "many",
        "toColumn": "Prueba",
        "toTable": "Test Data"
      },
      {
        "name": "ebf62a40-dc3e-fa64-0d32-9d551302b2e3",
        "fromColumn": "Test",
        "fromTable": "Saldo",
        "toCardinality": "many",
        "toColumn": "Prueba",
        "toTable": "Test Data"
      },
      {
        "name": "f4789811-5367-14c3-fbc0-b855711f6579",
        "fromColumn": "Test",
        "fromTable": "Dividendos",
        "toCardinality": "many",
        "toColumn": "Prueba",
        "toTable": "Test Data"
      }
    ],
    "sourceQueryCulture": "es-ES",
    "tables": [
      {
        "name": "Saldo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "Fecha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1ec5e515-964d-4d8f-affd-638428f188d7",
            "sourceColumn": "Fecha",
            "summarizeBy": "none"
          },
          {
            "name": "Saldo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "d49d5297-16fb-41eb-8b56-a0e3fed60451",
            "sourceColumn": "Saldo",
            "summarizeBy": "sum"
          },
          {
            "name": "Saldo Mes / Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "MONTH(Saldo[Fecha]) & \"-\" & YEAR(Saldo[Fecha])",
            "isDataTypeInferred": true,
            "lineageTag": "1b19ff95-91c8-47cc-ac64-f29ad1952f06",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "36174405-fe32-460a-84eb-e5d0409104be",
            "sourceColumn": "Año",
            "summarizeBy": "sum"
          },
          {
            "name": "Mes / Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd967406-667c-4b58-b922-0aec37656178",
            "sourceColumn": "Mes / Año",
            "summarizeBy": "sum"
          },
          {
            "name": "Valor liquidativo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "96f79b53-1c49-4143-812f-5645a3625f70",
            "sourceColumn": "Valor liquidativo",
            "summarizeBy": "none"
          },
          {
            "name": "Participaciones",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "694f704d-7a5a-4a7e-92d9-b4950f52b3c3",
            "sourceColumn": "Participaciones",
            "summarizeBy": "sum"
          },
          {
            "name": "Producto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67c082d9-6928-48b1-9c52-8e010a2f28ba",
            "sourceColumn": "Producto",
            "summarizeBy": "none"
          },
          {
            "name": "Importe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "9f3125ac-2f24-4852-b31f-2131b59074f4",
            "sourceColumn": "Importe",
            "summarizeBy": "sum"
          },
          {
            "name": "Beneficio Acumulado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "[Beneficio Hasta Fecha]",
            "isDataTypeInferred": true,
            "lineageTag": "ddf79f79-8ac3-40e0-9951-4b326865030d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Valor liquidativo (Moneda Extranjera)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7b0b18b9-99f9-49f4-873c-acdd5ccea043",
            "sourceColumn": "Valor liquidativo (Moneda Extranjera)",
            "summarizeBy": "sum"
          },
          {
            "name": "Cambio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c6d83b6-8f57-42dd-afcf-c8adc12901dc",
            "sourceColumn": "Cambio",
            "summarizeBy": "sum"
          },
          {
            "name": "Detalle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0b47d24-a148-4d57-845b-cc82671b812a",
            "sourceColumn": "Detalle",
            "summarizeBy": "none"
          },
          {
            "name": "Test",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "91f3a4c0-a337-4bd2-9215-e8dfc326cae0",
            "sourceColumn": "Test",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ead767c0-2b14-4c09-a56f-681fb4332782",
        "partitions": [
          {
            "name": "Saldo-7024361d-f96d-4192-a9ca-f02665bac21a",
            "mode": "import",
            "queryGroup": "Saldo",
            "source": {
              "expression": [
                "let",
                "    Origen = #\"Origen Data File\",",
                "    T_Saldo_Table = Origen{[Item=\"T_Saldo\",Kind=\"Table\"]}[Data],",
                "    #\"[Column][Add] Test\" = if Table.HasColumns(T_Saldo_Table, \"Test\") then T_Saldo_Table else Table.AddColumn(T_Saldo_Table, \"Test\", each \"Producción\"),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(#\"[Column][Add] Test\",{{\"Fecha\", type date}, {\"Producto\", type text}, {\"Saldo\", Currency.Type}, {\"Participaciones\", type number}, {\"Valor liquidativo\", Currency.Type}, {\"Detalle\", type text}, {\"Valor liquidativo (Moneda Extranjera)\", type number}, {\"Cambio\", type number}, {\"Test\", type text}}),",
                "    #\"Consulta anexada\" = Table.Combine({#\"Tipo cambiado\", #\"Transacciones Agrupadas\"}),",
                "    // Remove rows without Cash Balance. ",
                "    // These rows are those transactions without cash information because we don't have sotcks and price.",
                "    // The cash balance is calculated then in a measure as Last Cash Balance + all transactions value",
                "    #\"Filas filtradas\" = Table.SelectRows(#\"Consulta anexada\", each [Saldo] <> null and [Saldo] <> \"\"),",
                "    #\"[Remove] Duplicados Fecha / Producto\" = Table.Distinct(#\"Filas filtradas\", {\"Fecha\", \"Producto\"}),",
                "    #\"Año insertado\" = Table.AddColumn(#\"[Remove] Duplicados Fecha / Producto\", \"Año\", each Date.Year([Fecha]), Int64.Type),",
                "    #\"Agregar columna personalizada\" = Table.AddColumn(#\"Año insertado\", \"Mes / Año\", each Date.Year([Fecha]) * 100 + Date.Month([Fecha]), Int64.Type),",
                "    #\"[Order] Fecha\" = Table.Sort(#\"Agregar columna personalizada\",{{\"Fecha\", Order.Ascending}}),",
                "    Buffer = Table.Buffer(#\"[Order] Fecha\")",
                "in",
                "    Buffer"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Movimientos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "FECHA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "a09a56bc-aa99-46a9-91e6-a542be291175",
            "sourceColumn": "FECHA",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Movimiento.Índice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "370c035f-5b02-4f13-b0ed-cc8f9778dc3b",
            "sourceColumn": "Tipo Movimiento.Índice",
            "summarizeBy": "none"
          },
          {
            "name": "IMPORTE (€)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "ea1bfd0f-afe2-41ed-bbfc-16cf98afefbe",
            "sourceColumn": "IMPORTE (€)",
            "summarizeBy": "sum"
          },
          {
            "name": "Cantidad (€)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "f900df2c-1db4-43fb-9df6-2b3a1d30f65d",
            "sourceColumn": "Cantidad (€)",
            "summarizeBy": "none"
          },
          {
            "name": "Mes / Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "992d2225-3926-41e0-9ea4-b1049b30f931",
            "sourceColumn": "Mes / Año",
            "summarizeBy": "none"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "26ee2ef1-bb13-4594-9032-91ea663875c2",
            "sourceColumn": "Año",
            "summarizeBy": "sum"
          },
          {
            "name": "Detalle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e528b7a-5561-4fa5-894a-c0416c8441d4",
            "sourceColumn": "Detalle",
            "summarizeBy": "none"
          },
          {
            "name": "Test",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1520449c-7194-404a-85a2-aa3b02f80fc8",
            "sourceColumn": "Test",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d4a0e9fb-69d2-47ed-b104-d7bf44c733ad",
        "measures": [
          {
            "name": "Media Importe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "expression": "AVERAGE(Movimientos[IMPORTE (€)])",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "5660d254-b4b0-4155-8b14-1bb31109e467"
          }
        ],
        "partitions": [
          {
            "name": "Movimientos-b861a020-f47d-455f-8c0e-68d4cbdfb9bc",
            "mode": "import",
            "queryGroup": "Movimientos",
            "source": {
              "expression": [
                "let",
                "    Origen = #\"Movimientos Origen\",",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"FECHA\", type date}, {\"CLASIFICACIÓN\", type text}, {\"IMPORTE (€)\", Currency.Type}, {\"CATEGORÍA\", type text}, {\"SUBCATEGORÍA\", type text}, {\"DESCRIPCIÓN\", type text}, {\"Test\", type text}}),",
                "    #\"Filas filtradas\" = Table.SelectRows(#\"Tipo cambiado\", each ([#\"IMPORTE (€)\"] <> 0)),",
                "    #\"[Type] Gasto to $\" = Table.TransformColumnTypes(#\"Filas filtradas\",{{\"IMPORTE (€)\", Currency.Type}}),",
                "    #\"[Column] New Valor (ABS)\" = Table.AddColumn(#\"[Type] Gasto to $\", \"Cantidad (€)\", each Number.Abs([#\"IMPORTE (€)\"])),",
                "    #\"[Update] Importe de movimientos a 0\" = Table.ReplaceValue(#\"[Column] New Valor (ABS)\",each [#\"IMPORTE (€)\"], each if [TIPO] = \"Movimiento\" then 0 else [#\"IMPORTE (€)\"],Replacer.ReplaceValue,{\"IMPORTE (€)\"}),",
                "    #\"[Type] Importe To $\" = Table.TransformColumnTypes(#\"[Update] Importe de movimientos a 0\",{{\"IMPORTE (€)\", Currency.Type}, {\"Cantidad (€)\", Currency.Type}}),",
                "    #\"Consultas combinadas\" = Table.NestedJoin(#\"[Type] Importe To $\", {\"CLASIFICACIÓN\", \"CATEGORÍA\", \"SUBCATEGORÍA\", \"DESCRIPCIÓN\", \"TIPO\"}, #\"Tipo Movimiento\", {\"CLASIFICACIÓN\", \"CATEGORÍA\", \"SUBCATEGORÍA\", \"DESCRIPCIÓN\", \"TIPO\"}, \"Tipo Movimiento\", JoinKind.LeftOuter),",
                "    #\"Se expandió Tipo Movimiento\" = Table.ExpandTableColumn(#\"Consultas combinadas\", \"Tipo Movimiento\", {\"Índice\"}, {\"Tipo Movimiento.Índice\"}),",
                "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Se expandió Tipo Movimiento\",{\"FECHA\", \"IMPORTE (€)\", \"Detalle\", \"Test\", \"Cantidad (€)\", \"Tipo Movimiento.Índice\"}),",
                "    #\"Consulta anexada\" = Table.Combine({#\"Otras columnas quitadas\", #\"Pagos Especie\", #\"Cobros Especie\"}),",
                "    #\"Agregar columna personalizada\" = Table.AddColumn(#\"Consulta anexada\", \"Mes / Año\", each Text.Combine({Date.ToText([FECHA], \"MM\"), \"-\", Date.ToText([FECHA], \"yyyy\")}), type text),",
                "    #\"Año insertado\" = Table.AddColumn(#\"Agregar columna personalizada\", \"Año\", each Date.Year([FECHA]), Int64.Type)",
                "in",
                "    #\"Año insertado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Productos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Producto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb72cc39-4d34-41f7-89fc-186303c90419",
            "sourceColumn": "Producto",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c6e60ec-3117-4573-a585-645c823f1525",
            "sourceColumn": "Tipo",
            "summarizeBy": "none"
          },
          {
            "name": "Subtipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6f732fb-ddc6-4a9d-96b4-4fdcef0d66f6",
            "sourceColumn": "Subtipo",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Tipo Producto",
            "levels": [
              {
                "name": "Tipo",
                "column": "Tipo",
                "lineageTag": "17fea27c-a04f-4b55-a215-6759a0b5b7d3",
                "ordinal": 0
              },
              {
                "name": "Subtipo",
                "column": "Subtipo",
                "lineageTag": "eeb5d34a-4fe3-48a2-a497-c7c6de3a1a67",
                "ordinal": 1
              }
            ],
            "lineageTag": "49f49e0a-9cd4-4160-8509-85ca634d0c56"
          }
        ],
        "lineageTag": "2223fd4a-620e-4df7-821d-57b4570c079a",
        "partitions": [
          {
            "name": "Productos-144bfd82-24df-490f-bcd4-fe2beeb5a294",
            "mode": "import",
            "queryGroup": "Saldo",
            "source": {
              "expression": [
                "let",
                "    Origen = #\"Origen Data File\",",
                "    T_Saldo_Table = Origen{[Item=\"T_Elementos\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(T_Saldo_Table,{{\"Producto\", type text}, {\"Tipo\", type text}, {\"Subtipo\", type text}, {\"Detalle\", type text}}),",
                "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Tipo cambiado\",{\"Subtipo\", \"Tipo\", \"Producto\"}),",
                "    #\"Duplicados quitados\" = Table.Distinct(#\"Otras columnas quitadas\"),",
                "    #\"Columnas reordenadas\" = Table.ReorderColumns(#\"Duplicados quitados\",{\"Producto\", \"Tipo\", \"Subtipo\"})",
                "in",
                "    #\"Columnas reordenadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendario",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "dcf825e785e74503a96df2b72bd48657"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "0cdf2679-76e3-47e3-9a0e-8ad0f0abf8ad",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mes / Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "41682a5d-f986-404e-890a-e824ef7a7b45",
            "sourceColumn": "[Mes / Año]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8eea9fc2-3b80-4ee4-9f81-2fd79a80bb17",
            "sourceColumn": "[Año]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8f3a5477-2ad6-408a-9b6d-5ff56ab459e8",
            "sortByColumn": "Mes (Num.)",
            "sourceColumn": "[Mes]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f35f3a2c-a6de-46f4-974f-dc066a65b0d5",
            "sourceColumn": "[Día]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FinDeMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "IF(",
              "    'Calendario'[Date] = EOMONTH('Calendario'[Date], 0) || Calendario[Date] = MAX(Calendario[Date]),",
              "    1,",
              "    0",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "209ce894-8b63-47c0-a7f1-cc480309c462",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Mes (Num.)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5ea1c5c3-d568-487f-ad91-0763c8a59cb9",
            "sourceColumn": "[Mes (Num.)]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date Jerarquía",
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "5e8d41d0-e83c-4c9a-9c89-eb3b765a243a",
                "ordinal": 0
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "36c8a340-b3e1-415b-ba34-444a58d99276",
                "ordinal": 1
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "e419d57d-1ac2-4cfc-8a9a-19c191aa1209",
                "ordinal": 2
              }
            ],
            "lineageTag": "b6367a7f-cc53-4e49-9183-65993507b3c0"
          }
        ],
        "lineageTag": "587011a5-84bf-4545-a193-39fd0de29998",
        "partitions": [
          {
            "name": "Calendario-9bab029b-1aa5-4764-a97c-b35e816b1e04",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "ADDCOLUMNS(",
                "   CALENDAR(MIN(MIN(MIN(Saldo[Fecha]),MIN(Transacciones[Fecha])),MIN(Movimientos[FECHA])),MAX(MAX(MAX(Saldo[Fecha]),MAX(Transacciones[Fecha])),MAX(Movimientos[FECHA])))",
                "    , \"Mes / Año\" , YEAR([Date]) *100 + MONTH([Date])",
                "    , \"Año\", YEAR([Date])",
                "    , \"Mes\", FORMAT([Date],\"MMMM\")",
                "    , \"Mes (Num.)\", MONTH([Date])",
                "    , \"Día\", DAY([Date])",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Tipo Movimiento",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "columns": [
          {
            "name": "CLASIFICACIÓN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Tipo Movimiento\",\"TableItemName\":\"CLASIFICACIÓN Ingresos - Gastos\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9f7abbf-aa1d-4f24-b8d4-c072e9a04221",
            "sourceColumn": "CLASIFICACIÓN",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORÍA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f28acb2b-5cf5-4180-b679-2b6098b5fe81",
            "sourceColumn": "CATEGORÍA",
            "summarizeBy": "none"
          },
          {
            "name": "SUBCATEGORÍA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b023c00d-c9ee-49dd-8d62-4bfaddcc8b41",
            "sourceColumn": "SUBCATEGORÍA",
            "summarizeBy": "none"
          },
          {
            "name": "DESCRIPCIÓN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcf50715-a9dd-4b68-bfd7-5d93a99a9152",
            "sourceColumn": "DESCRIPCIÓN",
            "summarizeBy": "none"
          },
          {
            "name": "TIPO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfbdd520-588a-4700-8fdf-0b61322a9383",
            "sourceColumn": "TIPO",
            "summarizeBy": "none"
          },
          {
            "name": "Índice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e1446add-6aa3-4ca6-840f-9857a726cd94",
            "sourceColumn": "Índice",
            "summarizeBy": "none"
          },
          {
            "name": "CLASIFICACIÓN Ingresos - Gastos",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"t\",\"Entity\":\"Tipo Movimiento\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"CLASIFICACIÓN\"}}],\"GroupItems\":[{\"DisplayName\":\"(En blanco)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Ingresos Tras Impuestos\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"t\"}},\"Property\":\"CLASIFICACIÓN\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Hacienda'\"}}],[{\"Literal\":{\"Value\":\"'Iván'\"}}],[{\"Literal\":{\"Value\":\"'Rebeca'\"}}]]}}},{\"DisplayName\":\"Gastos (Sin Impuestos)\"}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('Tipo Movimiento'[CLASIFICACIÓN]),",
              "\t\"(En blanco)\",",
              "\t'Tipo Movimiento'[CLASIFICACIÓN] IN {\"Hacienda\",",
              "\t\t\"Iván\",",
              "\t\t\"Rebeca\"},",
              "\t\"Ingresos Tras Impuestos\",",
              "\t\"Gastos (Sin Impuestos)\"",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Tipo Movimiento"
                          }
                        },
                        "Property": "CLASIFICACIÓN"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "6afe50ef-0f96-44e5-9b4e-8054bff29ec7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "79a691e9-e5d7-43f9-a51f-2164edd3cd31",
        "partitions": [
          {
            "name": "Tipo Movimiento-4ba2f255-fce4-476e-ab7d-9bdc82fa9906",
            "mode": "import",
            "queryGroup": "Movimientos",
            "source": {
              "expression": [
                "let",
                "    Origen = #\"Origen Data File\",",
                "    T_Movimientos_Table = Origen{[Item=\"T_Movimientos\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(T_Movimientos_Table,{{\"FECHA\", type date}, {\"CLASIFICACIÓN\", type text}, {\"IMPORTE (€)\", Currency.Type}, {\"CATEGORÍA\", type text}, {\"SUBCATEGORÍA\", type text}, {\"DESCRIPCIÓN\", type text}}),",
                "    #\"Filas filtradas\" = Table.SelectRows(#\"Tipo cambiado\", each ([#\"IMPORTE (€)\"] <> 0)),",
                "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Filas filtradas\",{\"CLASIFICACIÓN\", \"CATEGORÍA\", \"SUBCATEGORÍA\", \"DESCRIPCIÓN\", \"TIPO\"}),",
                "    #\"Duplicados quitados\" = Table.Distinct(#\"Otras columnas quitadas\"),",
                "    #\"Consulta anexada\" = Table.Combine({#\"Duplicados quitados\", #\"Tipo Pago Especie\", #\"Tipo Cobro Especie\"}),",
                "    #\"Índice agregado\" = Table.AddIndexColumn(#\"Consulta anexada\", \"Índice\", 0, 1, Int64.Type),",
                "    #\"Columnas reordenadas\" = Table.ReorderColumns(#\"Índice agregado\",{\"Índice\", \"CLASIFICACIÓN\", \"CATEGORÍA\", \"SUBCATEGORÍA\", \"DESCRIPCIÓN\", \"TIPO\"})",
                "in",
                "    #\"Columnas reordenadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas Saldo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "lineageTag": "d5a0786a-7d7e-410d-9408-bba78857846b",
        "measures": [
          {
            "name": "Saldo Último",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    SUMX(",
              "        VALUES(Productos[Producto]),",
              "        VAR UltimaFechaSaldoParaEsteProd = CALCULATE(MAX(Saldo[Fecha]), NOT(ISBLANK(Saldo[Saldo])))",
              "",
              "        RETURN",
              "            CALCULATE(",
              "                    SUM(Saldo[Saldo]),       ",
              "                    Saldo[Fecha] = UltimaFechaSaldoParaEsteProd            ",
              "            )",
              "            +",
              "            CALCULATE(",
              "                    SUM(Transacciones[Total Bruto]),       ",
              "                    Transacciones[Fecha] > UltimaFechaSaldoParaEsteProd            ",
              "            )",
              "    )",
              "    , Calendario[Date] <= MAX(Calendario[Date])",
              ")"
            ],
            "lineageTag": "a39857b5-e2b6-4745-9850-1058b0c0f5f6"
          },
          {
            "name": "Saldo Inversiones",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": [
              "",
              "CALCULATE(",
              "    [Saldo Último]",
              "    , FILTER(Productos, CONTAINSSTRING(Productos[Tipo], \"Renta\"))",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "71727381-c02e-47cb-98b6-5a234aaf57e4"
          },
          {
            "name": "Incremeto Saldo Desde Referencia (%)",
            "displayFolder": "Beneficio",
            "expression": [
              "",
              "CALCULATE(",
              "    'Medidas Saldo'[Incremento % Periodo]",
              "    , FILTER(",
              "        Calendario",
              "        ,Calendario[Año] >= [Valor Año Referencia]",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "39070c3a-9918-450e-8b08-b04019cccc19"
          },
          {
            "name": "Inversión Realizada Inicio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "displayFolder": "Inversión",
            "expression": [
              "",
              "",
              "SUMX(",
              "    VALUES(Productos[Producto])",
              "    , CALCULATE(        ",
              "        [Ingresos Inversion]",
              "        , ",
              "        Calendario[Date] < MIN(Calendario[Date])",
              "    )",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "991ca7f4-4927-4132-9d17-ce854a1e5cf1"
          },
          {
            "name": "Beneficio Periodo",
            "displayFolder": "Beneficio",
            "expression": [
              "",
              "",
              "[Beneficio Inversión] + [Dividendos Netos]"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "9e7830f5-83ce-449d-8c56-3caea8888d31"
          },
          {
            "name": "Incremento Normalizado Saldo Periodo (%)",
            "displayFolder": "Beneficio",
            "expression": [
              "",
              "DIVIDE([Beneficio Periodo],[Capital Invertido Medio],0)"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "3b69a7c0-385d-48d7-bffc-d4e6174fdc67"
          },
          {
            "name": "Ingresos Inversion",
            "displayFolder": "Inversión",
            "expression": [
              "",
              "    CALCULATE(",
              "        [Ingresos Relevantes Entre Fechas (Sin Saldo de Inicio)]",
              "        , KEEPFILTERS(CONTAINSSTRING(Productos[Tipo], \"Renta\"))",
              "    )"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "a0796263-e776-40da-810e-9a2ec6b48e19"
          },
          {
            "name": "Capital Invertido Medio",
            "displayFolder": "Inversión",
            "expression": [
              "",
              "",
              "VAR capital_inicial = [Saldo Fecha Inicio]",
              "VAR dias_inversion = [Días Inversion]",
              "",
              "RETURN",
              "SUMX(",
              "    VALUES(Saldo[Fecha])",
              "    ,",
              "    VAR fecha_actual = CALCULATE(SELECTEDVALUE(Saldo[Fecha]))",
              "    VAR fecha_posterior = ",
              "        COALESCE(",
              "            CALCULATE(",
              "                MIN(Saldo[Fecha]), Saldo[Fecha] > fecha_actual",
              "            )",
              "        , MIN(MAX(Calendario[Date]), TODAY())",
              "        )",
              "",
              "    RETURN ",
              "",
              "       DIVIDE(",
              "        DATEDIFF(fecha_actual, fecha_posterior, DAY) ",
              "        *",
              "        (CALCULATE(           ",
              "            [Ingresos Relevantes Entre Fechas (Sin Saldo de Inicio)]",
              "            , KEEPFILTERS(Calendario[Date] <= fecha_actual)",
              "            , Saldo[Fecha] <= fecha_actual",
              "        )",
              "        +",
              "        capital_inicial)",
              "        , dias_inversion",
              "       )",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "8b55bfd6-0bb6-4178-8516-2c70dc67bc35"
          },
          {
            "name": "Tiempo Inversión(Meses)",
            "displayFolder": "Inversión",
            "expression": "MAXX(VALUES(Productos[Producto]), DISTINCTCOUNT(Saldo[Mes / Año]))",
            "formatString": "0",
            "lineageTag": "85d4c53f-3931-46b2-89df-2ff90e9382d4"
          },
          {
            "name": "Incremento Normalizado Anual (%)",
            "displayFolder": "Beneficio",
            "expression": [
              "",
              "VAR Base      = 1 + [Incremento Normalizado Saldo Periodo (%)]",
              "VAR Exponente = DIVIDE(",
              "                    1,",
              "                    ([Tiempo Inversión(Meses)] / 12),",
              "                    0",
              "                )",
              "RETURN",
              "    IF(",
              "        OR(",
              "            Base <= 0,           -- Evita raíz de números negativos o cero",
              "            Exponente <= 0       -- Evita exponente cero/negativo",
              "        ),",
              "        BLANK(),                -- O el valor alternativo que prefieras",
              "        POWER(Base, Exponente) - 1",
              "    )"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "64abfa5d-68a7-472d-a819-ac2f04eb3172"
          },
          {
            "name": "Saldo Mes Anterior",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": [
              "",
              "CLOSINGBALANCEMONTH(SUM(Saldo[Saldo]), PARALLELPERIOD(Saldo[Fecha], -1, MONTH), ALL(Calendario))"
            ],
            "formatString": "\"€\"\\ #,0.00;-\"€\"\\ #,0.00;\"€\"\\ #,0.00",
            "lineageTag": "761bee12-a2cc-4758-a067-a9ae4b3c6ab7"
          },
          {
            "name": "Saldo Año Anterior",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": [
              "",
              "CLOSINGBALANCEYEAR(SUM(Saldo[Saldo]), PARALLELPERIOD(Saldo[Fecha], -1, YEAR), ALL(Calendario))"
            ],
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "ad4fce47-f6de-4494-a9be-3eb81478ea57"
          },
          {
            "name": "Incremento Saldo Periodo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "displayFolder": "Beneficio",
            "expression": "[Saldo Último] - [Saldo Fecha Inicio]",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "ed294a56-6b4a-4e40-8955-134eb22448b7"
          },
          {
            "name": "Gastos no Computados Periodo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Gastos",
            "expression": [
              "",
              "CALCULATE(",
              "    [Incremento Saldo Periodo] - [Beneficio Inversión] - [Movimientos Totales Periodo]",
              "    , REMOVEFILTERS('Tipo Movimiento')",
              ")"
            ],
            "lineageTag": "7179a8be-9929-4647-ae17-d26b36074a74"
          },
          {
            "name": "Saldo Fecha Inicio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    SUMX(",
              "        VALUES(Productos[Producto]),",
              "        VAR UltimaFechaSaldoParaEsteProd = CALCULATE(MAX(Saldo[Fecha]), NOT(ISBLANK(Saldo[Saldo])))",
              "",
              "        RETURN",
              "            CALCULATE(",
              "                    SUM(Saldo[Saldo]),       ",
              "                    Saldo[Fecha] = UltimaFechaSaldoParaEsteProd            ",
              "            )",
              "            +",
              "            CALCULATE(",
              "                    SUM(Transacciones[Total Bruto]),       ",
              "                    Transacciones[Fecha] > UltimaFechaSaldoParaEsteProd            ",
              "            )",
              "    )",
              "    , Calendario[Date] < MIN(Calendario[Date])",
              ")",
              "",
              "/*CALCULATE(",
              "    SUMX(",
              "        CALCULATETABLE(",
              "            VALUES(Saldo[Producto])",
              "            , REMOVEFILTERS(Calendario)",
              "        )",
              "        ,",
              "        VAR Prod = Saldo[Producto]",
              "        VAR UltimaFechaParaEsteProd =",
              "            CALCULATE(",
              "                MAX(Saldo[Fecha]),",
              "                Calendario[Date] < MIN(Calendario[Date])",
              "            )",
              "",
              "        RETURN ",
              "            CALCULATE(",
              "                SUM(Saldo[Saldo]),            ",
              "                ALL(Saldo),",
              "                Saldo[Producto] = Prod,",
              "                Saldo[Fecha] = UltimaFechaParaEsteProd            ",
              "            )",
              "    )",
              ")*/"
            ],
            "lineageTag": "a63ea999-5957-4646-ac5b-90819685d678"
          },
          {
            "name": "Fecha Inicial",
            "expression": "MIN(Saldo[Fecha])",
            "formatString": "Short Date",
            "lineageTag": "4c15a658-8363-445e-9dc0-7d900cf289c0"
          },
          {
            "name": "Ingresos Relevantes Entre Fechas (Sin Saldo de Inicio)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Inversión",
            "expression": [
              "",
              "",
              "    CALCULATE(",
              "        SUM('Transacciones'[Total Bruto])",
              "        , Transacciones[Tipo Transacción] IN {\"Compra\",\"Venta\"}",
              "    )"
            ],
            "lineageTag": "06e766eb-4804-4b20-8707-473b7cdc7a6c"
          },
          {
            "name": "Inversion Total Realizada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "displayFolder": "Inversión",
            "expression": "[Inversión Realizada Inicio] + [Ingresos Relevantes Entre Fechas (Sin Saldo de Inicio)]",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "6641769b-fee3-4f19-96c0-b94a8338b925"
          },
          {
            "name": "Primer Saldo Seleccion",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": [
              "",
              "",
              "CALCULATE (",
              "    CALCULATE(",
              "        [Saldo Último]",
              "        ,",
              "        Calendario[Date] <= MIN(Saldo[Fecha])",
              "    ) ",
              "    , ALLSELECTED(Calendario[Date])",
              ")"
            ],
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "a3493487-9cb3-4010-b392-c6996417cd4b"
          },
          {
            "name": "Beneficio Hasta Fecha",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Beneficio",
            "expression": [
              "",
              "",
              "VAR fecha_actual = SELECTEDVALUE(Calendario[Date])",
              "",
              "RETURN ",
              "CALCULATE(",
              "    [Beneficio Periodo],",
              "    Calendario[Date] <= fecha_actual,",
              "    ALLSELECTED(Calendario)",
              ")",
              "    "
            ],
            "lineageTag": "09038fab-5a9f-49e2-8577-4f042c2c4d7f"
          },
          {
            "name": "Incremento Normalizado Hasta la Fecha",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Beneficio",
            "expression": [
              "",
              "",
              "VAR fecha_actual = MAX(Calendario[Date])",
              "",
              "RETURN ",
              "CALCULATE(",
              "   CALCULATE(",
              "        [Incremento Normalizado Saldo Periodo (%)]",
              "        , KEEPFILTERS(Calendario[Date] <= fecha_actual)",
              "    )",
              "    , ALLSELECTED(Calendario)",
              ")",
              "    "
            ],
            "lineageTag": "f3ba3cb7-208e-47d0-b62b-616e98ea5672"
          },
          {
            "name": "Saldo Esperado Sin Beneficios",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": "[Saldo Mes Anterior] + [Ingresos Inversion]",
            "lineageTag": "6b181c5d-622e-4789-aff1-5841a5918035"
          },
          {
            "name": "% Sobre esperado",
            "displayFolder": "Saldo",
            "expression": [
              "",
              "IF([Ingresos Inversion] = 0, BLANK(), ABS((SUM(Saldo[Saldo]) - [Saldo Mes Anterior]) / [Ingresos Inversion]))"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "8fe86df5-e0e2-4461-af39-90b5759b2bdd"
          },
          {
            "name": "Dividendos Netos",
            "displayFolder": "Inversión",
            "expression": "[Dividendos Bruto]*(1-[Tipo IRPF Anual])",
            "formatString": "\"€\"\\ #,0.00;-\"€\"\\ #,0.00;\"€\"\\ #,0.00",
            "lineageTag": "8c6f3656-cf65-44f3-85c6-8d000bb44e47"
          },
          {
            "name": "Beneficio Inversión",
            "displayFolder": "Beneficio",
            "expression": [
              "",
              "CALCULATE( ",
              "    [Saldo Último] - [Ingresos Inversion] - [Saldo Fecha Inicio] ",
              "    , KEEPFILTERS(CONTAINSSTRING(Productos[Tipo], \"Renta\"))",
              ")"
            ],
            "formatString": "\"€\"\\ #,0.00;-\"€\"\\ #,0.00;\"€\"\\ #,0.00",
            "lineageTag": "56ea0509-eec2-4483-9b9a-dd3dc5420fb9"
          },
          {
            "name": "Participaciones Actuales",
            "displayFolder": "Saldo",
            "expression": [
              "",
              "",
              "VAR ultima_fecha = MAX ( Calendario[Date] )",
              "",
              "RETURN",
              "IF (",
              "    ISFILTERED ( Productos[Producto] ),",
              "    ROUND (",
              "        CALCULATE (",
              "            SUM ( Transacciones[Participaciones] ),",
              "            Transacciones[Tipo Transacción] <> \"Dividendos\",",
              "            Calendario[Date] <= ultima_fecha",
              "        ),",
              "        3",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "42d391dd-ae26-42fc-823a-bcf679760487"
          },
          {
            "name": "Valor Liquidativo Actual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(Transacciones[Producto]) && [Participaciones Actuales] > 0.001, ",
              "    DIVIDE([Saldo Último],[Participaciones Actuales],BLANK())",
              ")"
            ],
            "lineageTag": "12189525-96a3-4024-9dfc-e646c56ed343"
          },
          {
            "name": "Valor Liq. Compra",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": [
              "",
              "",
              "IF(",
              "    HASONEVALUE(Productos[Producto]) && [Participaciones Actuales] > 0.001, ",
              "    DIVIDE([Inversion Total Realizada], [Participaciones Actuales])",
              ")"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "4fba88dd-13ca-46a0-b1c0-1a9738f2e5c4"
          },
          {
            "name": "Valor Liq. Compra Transaccion",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Inversión",
            "expression": [
              "",
              "SUMX(",
              "    CALCULATETABLE(VALUES('Transacciones'[ID]), ALLEXCEPT('Transacciones', Productos)), CALCULATE([Valor Liq. Compra], Calendario[Date] <= SELECTEDVALUE('Transacciones'[Fecha])))"
            ],
            "lineageTag": "ce2867f4-5590-4b39-aebe-b5be07c9c2e4"
          },
          {
            "name": "SV",
            "displayFolder": "Inversión",
            "expression": "MINX(VALUES(Calendario[Date]), CALCULATE([Min Date](Calendario[Date]), Calendario[Date] <= SELECTEDVALUE('Transacciones'[Fecha])))",
            "formatString": "General Date",
            "lineageTag": "65295c28-ab55-4d9e-9f1b-50ebce2cbbef"
          },
          {
            "name": "Dividendos Bruto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Inversión",
            "expression": "SUM(Dividendos[Total Bruto])",
            "lineageTag": "7fffd7a0-0481-4b1a-b92e-e36310649278"
          },
          {
            "name": "Valor Liquidativo Normalizado Compra Periodo",
            "displayFolder": "Saldo",
            "expression": [
              "",
              "",
              "// Representa el valor liquidativo medio normalizado de compra de las acciones durante el período",
              "// Para calcularlo, se usa el valor actual y el incremento normalizado durante el período",
              "// Esto nos lleva a tener en cuenta no solo las compras realizadas, sino cuanto tiempo llevamos invertidos con cada uno de las inversiones realizadas",
              "DIVIDE([Valor Liquidativo Actual], (1 + [Incremento Normalizado Saldo Periodo (%)]))"
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "09390001-c412-4c58-b427-f6be554eec85"
          },
          {
            "name": "Días Inversion",
            "displayFolder": "Inversión",
            "expression": "DATEDIFF(MIN(Saldo[Fecha]),MAX(Saldo[Fecha]),DAY)",
            "formatString": "0",
            "lineageTag": "92557d77-fa48-4bd0-bc27-06b0b0508207"
          },
          {
            "name": "Participaciones Acumuladas",
            "displayFolder": "Saldo",
            "expression": [
              "",
              "",
              "VAR ultima_fecha = MAX ( Transacciones[Fecha])",
              "",
              "RETURN",
              "IF (",
              "    HASONEVALUE ( Transacciones[Producto] ),",
              "    ROUND (",
              "        CALCULATE (",
              "            SUM ( Transacciones[Participaciones] ),",
              "            REMOVEFILTERS ( Transacciones ),",
              "            FILTER (",
              "                ALL ( Transacciones ),",
              "                Transacciones[Tipo Transacción] <> \"Dividendos\"",
              "                    && Transacciones[Producto] IN VALUES ( Transacciones[Producto] )",
              "                    && Transacciones[Fecha] <= ultima_fecha",
              "            )",
              "        ),",
              "        3",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "3ee8e587-8667-4318-aadc-6d41644e629a"
          },
          {
            "name": "Incremento % Periodo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Beneficio",
            "expression": "DIVIDE([Incremento Saldo Periodo], [Saldo Fecha Inicio])",
            "lineageTag": "c8aaff31-7dba-45cf-b78b-9fa583e7fb88"
          },
          {
            "name": "Movimientos Totales Periodo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "displayFolder": "Saldo",
            "expression": "SUM(Movimientos[IMPORTE (€)])",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "3f8cc06e-462b-4dc7-94ac-1ef6fde8f585"
          },
          {
            "name": "Beneficio Acumulado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Beneficio",
            "expression": [
              "",
              "",
              "VAR fecha_actual = SELECTEDVALUE(Calendario[Date])",
              "VAR fecha_inicial = CALCULATE(MIN(Calendario[Date]), ALLSELECTED(Calendario[Date]))",
              "",
              "RETURN",
              "CALCULATE(",
              "    SUMX(",
              "        VALUES(Saldo[Producto]), ",
              "        VAR FechaUltima =",
              "            CALCULATE (",
              "                LASTNONBLANK(Saldo[Fecha], SUM(Saldo[Beneficio Acumulado]))",
              "            )",
              "        ",
              "        RETURN",
              "            CALCULATE (",
              "                MAX(Saldo[Beneficio Acumulado]),",
              "                Saldo[Fecha] = FechaUltima",
              "            )",
              "    )",
              "    , Calendario[Date] <= fecha_actual",
              ")",
              ""
            ],
            "lineageTag": "a0d1e788-b548-4cae-9443-bcc70e28feef"
          }
        ],
        "partitions": [
          {
            "name": "Medidas Saldo-33aeef08-3cdc-4fa0-95f6-080e8879d97f",
            "mode": "import",
            "queryGroup": "Saldo",
            "source": {
              "expression": [
                "let",
                "    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"Columna1\", type text}}),",
                "    #\"Columnas quitadas\" = Table.RemoveColumns(#\"Tipo cambiado\",{\"Columna1\"})",
                "in",
                "    #\"Columnas quitadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Año Referencia",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "10c52e0b5c144b689f298889175a9205"
          }
        ],
        "columns": [
          {
            "name": "Año Referencia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "06ce6efd-1360-4da8-8e40-445839639b60",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f4913a55-8049-44ba-a3dc-dc5a7f69a427",
        "measures": [
          {
            "name": "Valor Año Referencia",
            "expression": "SELECTEDVALUE('Año Referencia'[Año Referencia], 2020)",
            "formatString": "0",
            "lineageTag": "b32f0955-93c0-4a10-89da-6fc1feb86cf4"
          }
        ],
        "partitions": [
          {
            "name": "Año Referencia-622cac0f-a92d-4c65-81c7-0525196ca02b",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(2005, 2030, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Medidas Movimientos",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "lineageTag": "30bd2545-c205-453b-a2f3-858bc695c399",
        "measures": [
          {
            "name": "Fecha Último Movimiento",
            "expression": [
              "",
              "CALCULATE(",
              "    CALCULATE(",
              "        MAX(Movimientos[FECHA])",
              "        , ALL(Movimientos)    ",
              "    )",
              "    , ALL(Calendario)    ",
              "    , ALL('Tipo Movimiento')",
              ")          "
            ],
            "formatString": "General Date",
            "lineageTag": "cac53a3a-446b-43f2-a2fe-85009b1828b6"
          },
          {
            "name": "Media Mensual Último Año (€)",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    DIVIDE(SUM(Movimientos[IMPORTE (€)]), DISTINCTCOUNT(Movimientos[Mes / Año]))               ",
              "    , DATESINPERIOD(Calendario[Date], ENDOFMONTH(Calendario[Date]), -1, YEAR)",
              ")   "
            ],
            "formatString": "0.00",
            "lineageTag": "63c97ab6-782d-4e44-a120-dfc8ee1f3f14"
          },
          {
            "name": "Media Mismo Período Otros Años",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR yearSelected = SELECTEDVALUE(Calendario[Año])",
              "VAR isNeeded = ISBLANK(yearSelected)",
              "",
              "RETURN ",
              "",
              "    IF (",
              "        isNeeded",
              "        , BLANK()",
              "        , CALCULATE(",
              "            CALCULATE(",
              "                DIVIDE(SUM(Movimientos[IMPORTE (€)]), DISTINCTCOUNT(Calendario[Año]))                ",
              "                , KEEPFILTERS(Calendario[Año] <> yearSelected)",
              "            )",
              "            , ALLSELECTED(Calendario[Año])",
              "        )",
              "    )    "
            ],
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "06738dd3-a3e1-4ff8-bf5e-ffcd8be4ba12"
          },
          {
            "name": "Desviación Media Otros Años",
            "expression": [
              "",
              "IF ( ISBLANK('Medidas Movimientos'[Media Mismo Período Otros Años])",
              "    , BLANK()",
              "    , DIVIDE(",
              "        ABS(SUM(Movimientos[IMPORTE (€)]) - 'Medidas Movimientos'[Media Mismo Período Otros Años]) ",
              "        , ABS('Medidas Movimientos'[Media Mismo Período Otros Años])",
              "        , 0",
              "    )",
              ")"
            ],
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "b729ca55-7db9-40bf-ba4c-56a9e341073b"
          },
          {
            "name": "Meses Activos Ultimo Año",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(Movimientos[Mes / Año])",
              "    , DATESINPERIOD(Calendario[Date], ENDOFMONTH(Calendario[Date]), -1, YEAR)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "1395d250-1cf8-491a-97dc-5abb98ff635f"
          },
          {
            "name": "Importe Ultimo Año",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Movimientos[IMPORTE (€)])",
              "    , DATESINPERIOD(Calendario[Date], ENDOFMONTH(Calendario[Date]), -1, YEAR)",
              ")"
            ],
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "d93b79a1-e089-4e2b-8ad3-94d286abb4f6"
          },
          {
            "name": "Min Date",
            "expression": "MIN(Calendario[Date])",
            "formatString": "General Date",
            "lineageTag": "2d399e19-d882-430d-8417-22a6f38102a5"
          },
          {
            "name": "Futuro",
            "expression": [
              "",
              "IF (",
              "    OR(",
              "        MIN(Calendario[Año]) > YEAR([Fecha Último Movimiento])",
              "        , AND(",
              "            MIN(Calendario[Año]) = YEAR([Fecha Último Movimiento])",
              "            , MIN(Calendario[Mes (Num.)]) > MONTH([Fecha Último Movimiento])      ",
              "        )",
              "    )",
              "    , 1",
              "    , 0",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a92be042-59b6-4e8c-95f7-8490b90385f9"
          },
          {
            "name": "Mes Sin Datos",
            "expression": "IF(AND(ISBLANK(SUM(Movimientos[IMPORTE (€)])),ISBLANK([Media Mismo Período Otros Años])),1,0)",
            "formatString": "0",
            "lineageTag": "b6775187-8c2a-480d-990d-e4844ab973ae"
          },
          {
            "name": "Ingresos Tras Impuestos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "expression": "CALCULATE(SUM(Movimientos[IMPORTE (€)]), 'Tipo Movimiento'[CLASIFICACIÓN Ingresos - Gastos] = \"Ingresos Tras Impuestos\")",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "ad460d72-265c-45df-b4e9-de506b958ef7"
          },
          {
            "name": "Gastos (Sin Impuestos)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "expression": "CALCULATE(SUM(Movimientos[IMPORTE (€)]), 'Tipo Movimiento'[CLASIFICACIÓN Ingresos - Gastos] = \"Gastos (Sin Impuestos)\")",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "99781220-40b6-4b38-adae-b05b9c7aba8e"
          }
        ],
        "partitions": [
          {
            "name": "Medidas Movimientos-35e0bd82-4484-4b77-b9be-901ffda1a2f1",
            "mode": "import",
            "queryGroup": "Movimientos",
            "source": {
              "expression": [
                "let",
                "    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"Columna1\", type text}}),",
                "    #\"Columnas quitadas\" = Table.RemoveColumns(#\"Tipo cambiado\",{\"Columna1\"})",
                "in",
                "    #\"Columnas quitadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dividendos",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Fecha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7dcc79d3-a7bc-471f-b176-470c31f02efd",
            "sourceColumn": "Fecha",
            "summarizeBy": "none"
          },
          {
            "name": "Producto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab2b8ccc-4afa-4cd8-a28e-bd3b2ef63f00",
            "sourceColumn": "Producto",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Transacción",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb677d99-bd46-437d-8407-69a1578e4c17",
            "sourceColumn": "Tipo Transacción",
            "summarizeBy": "none"
          },
          {
            "name": "Participaciones",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ba043788-029b-4fd5-b9cb-179388d7cf1f",
            "sourceColumn": "Participaciones",
            "summarizeBy": "sum"
          },
          {
            "name": "Comisión",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "0",
            "lineageTag": "0219d315-fc08-4f55-8d78-8e5c51f4fe7c",
            "sourceColumn": "Comisión",
            "summarizeBy": "sum"
          },
          {
            "name": "Retenido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "180a1777-6806-403d-ba4a-e9686b349eea",
            "sourceColumn": "Retenido",
            "summarizeBy": "sum"
          },
          {
            "name": "Año IRPF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4d223b0a-23c6-45c0-8c4b-904a821f9493",
            "sourceColumn": "Año IRPF",
            "summarizeBy": "sum"
          },
          {
            "name": "Año IRPF Fijado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "689f7cdd-01f4-4eaa-bbd5-4f2a280ac2c7",
            "sourceColumn": "Año IRPF Fijado",
            "summarizeBy": "none"
          },
          {
            "name": "Precio Participación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "e0088e02-bb43-474d-8266-621b384472cb",
            "sourceColumn": "Precio Participación",
            "summarizeBy": "sum"
          },
          {
            "name": "Cambio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "8b10b847-0934-49e1-899d-183ff3c64a95",
            "sourceColumn": "Cambio",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Bruto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "7028c846-bf67-4fcb-986b-75d7871d0df4",
            "sourceColumn": "Total Bruto",
            "summarizeBy": "sum"
          },
          {
            "name": "Renta Bruta Obtenida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "4bc6e92f-7575-454f-ba6f-eaaca15f0704",
            "sourceColumn": "Renta Bruta Obtenida",
            "summarizeBy": "sum"
          },
          {
            "name": "Cuenta Producto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f91cfd13-202a-41f2-9a77-291fc4f4bbd9",
            "sourceColumn": "Cuenta Producto",
            "summarizeBy": "none"
          },
          {
            "name": "Producto Contraparte",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "913012c0-cfc4-476b-a750-65b8a6fe6025",
            "sourceColumn": "Producto Contraparte",
            "summarizeBy": "none"
          },
          {
            "name": "Cuenta Contraparte",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "173efb79-7d7e-4405-849c-c0c103d496e1",
            "sourceColumn": "Cuenta Contraparte",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "73da1f3b-0e64-4580-a3b0-4ba944e3dbab",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "0d05635e-db06-457a-8e54-a63a4f43dd3f",
            "sourceColumn": "Hora",
            "summarizeBy": "none"
          },
          {
            "name": "Precio (Moneda Transacción)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "7d48878b-0226-407a-80d3-792d77d23487",
            "sourceColumn": "Precio (Moneda Transacción)",
            "summarizeBy": "sum"
          },
          {
            "name": "Importe Bruto (Moneda Transacción)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "2e0484f1-32be-4930-b43a-cbd68b16d5b2",
            "sourceColumn": "Importe Bruto (Moneda Transacción)",
            "summarizeBy": "sum"
          },
          {
            "name": "Retenido (Moneda Transacción)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "a99e4420-efc5-411a-bd3c-d12747451349",
            "sourceColumn": "Retenido (Moneda Transacción)",
            "summarizeBy": "sum"
          },
          {
            "name": "Comisión (Moneda Transacción)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "e6dda79a-6cd5-46a3-b94a-d649d1542b26",
            "sourceColumn": "Comisión (Moneda Transacción)",
            "summarizeBy": "sum"
          },
          {
            "name": "Moneda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e07a56cf-4149-4ba0-a7b7-094fdbe54841",
            "sourceColumn": "Moneda",
            "summarizeBy": "none"
          },
          {
            "name": "Detalle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3e20918-45a6-4ef7-9ef6-09c4641debc4",
            "sourceColumn": "Detalle",
            "summarizeBy": "none"
          },
          {
            "name": "Test",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2bc3094-e9bc-49b7-a66f-5f96e27e5764",
            "sourceColumn": "Test",
            "summarizeBy": "none"
          },
          {
            "name": "Importe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "0",
            "lineageTag": "6a0938ed-1289-4bb1-86da-aabcefba700c",
            "sourceColumn": "Importe",
            "summarizeBy": "sum"
          },
          {
            "name": "Participaciones Acumuladas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "b85cd9ea-bf6a-4070-bdf1-e9936dbcf720",
            "sourceColumn": "Participaciones Acumuladas",
            "summarizeBy": "sum"
          },
          {
            "name": "Precio Medio Hasta Transacción",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "44d95f1d-8dd9-4d74-b2e9-4e7f719465d6",
            "sourceColumn": "Precio Medio Hasta Transacción",
            "summarizeBy": "sum"
          },
          {
            "name": "FIFO Beneficio / Pérdida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "4d493ba9-9611-464e-a485-26e10332e7e9",
            "sourceColumn": "FIFO Beneficio / Pérdida",
            "summarizeBy": "sum"
          },
          {
            "name": "IRPF - Ganancia / Pérdida Imputable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "a37df76f-f6d6-40e1-8995-5d7a9d5dbe18",
            "sourceColumn": "IRPF - Ganancia / Pérdida Imputable",
            "summarizeBy": "sum"
          },
          {
            "name": "IRPF - Ajuste Diferido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "4534ac08-05c3-4cbd-b691-5d59f76e8a74",
            "sourceColumn": "IRPF - Ajuste Diferido",
            "summarizeBy": "sum"
          },
          {
            "name": "Fecha/Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "cc131b02-35d0-43a3-9aee-d87d22a985ec",
            "sourceColumn": "Fecha/Hora",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_b9da2914-fd53-4f32-b21c-39fa4c9bbfb1"
                },
                "isDefault": true,
                "relationship": "3a5f943a-4678-40ea-b351-5487beb493ac"
              }
            ]
          }
        ],
        "lineageTag": "71d662a6-d45e-4164-ac31-d301ddfcca99",
        "partitions": [
          {
            "name": "Dividendos",
            "mode": "import",
            "queryGroup": "Saldo",
            "source": {
              "expression": [
                "let",
                "    Origen = Transacciones,",
                "    #\"Filas filtradas\" = Table.SelectRows(Origen, each ([Tipo Transacción] = \"Dividendos\"))",
                "in",
                "    #\"Filas filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas Transacciones",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "1119b22a-9d0a-4769-8f0c-4498053d07e1",
        "measures": [
          {
            "name": "Participaciones Vendidas Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR products = VALUES('Transacciones'[Producto])",
              "Var dates = VALUES(Calendario[Date])",
              "",
              "RETURN SUMX(",
              "    CALCULATETABLE(",
              "        SELECTCOLUMNS('Transacciones', 'Transacciones'[Producto], 'Transacciones'[Participaciones])                ",
              "        , ALL('Transacciones')",
              "        , products",
              "        , dates",
              "        , 'Transacciones'[Tipo Transacción] = \"Venta\"                ",
              "    )",
              "    , 'Transacciones'[Participaciones] * -1    ",
              ")"
            ],
            "lineageTag": "91842e8e-345f-4571-8084-fb58f28df508"
          },
          {
            "name": "Participaciones Vendidas de Transacción De Compra",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR participaciones_totales_compradas = ",
              "    CALCULATE(",
              "        SELECTEDVALUE('Transacciones'[Participaciones]),",
              "        Transacciones[Tipo Transacción] = \"Compra\"",
              "    )",
              "",
              "VAR participaciones_vendidas = ",
              "MAX(",
              "    MIN(",
              "        MAX(BLANK(), [Participaciones Vendidas Total] - ([Participaciones Compradas Hasta Última Transacción] - participaciones_totales_compradas))",
              "        , participaciones_totales_compradas",
              "    )",
              "    ,BLANK()",
              ")",
              "",
              "RETURN  participaciones_vendidas",
              ""
            ],
            "lineageTag": "c5d21235-30ce-4183-819f-7620c7599e88"
          },
          {
            "name": "Participaciones Compradas Hasta Última Transacción",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR productos = VALUES(Transacciones[Producto])",
              "VAR fecha_transaccion = MAX('Transacciones'[Fecha])",
              "",
              "RETURN CALCULATE(",
              "    SUM('Transacciones'[Participaciones])",
              "    , Calendario[Date] <= fecha_transaccion",
              "    , ALL(Transacciones)",
              "    , productos",
              "    , 'Transacciones'[Tipo Transacción] = \"Compra\"",
              ")",
              ""
            ],
            "lineageTag": "8b3509c2-e185-4171-b8ce-1cd0ecb2e9fa"
          },
          {
            "name": "Coste Participaciones Vendidas Transaccion",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR products = VALUES('Transacciones'[Producto])",
              "",
              "VAR coste = ",
              "    SUMX(",
              "        CALCULATETABLE(",
              "            SELECTCOLUMNS('Transacciones', 'Transacciones'[Producto], 'Transacciones'[Participaciones], 'Transacciones'[Precio participación], Transacciones[Tipo Transacción])                       ",
              "            , products",
              "            , Transacciones[Tipo Transacción] = \"Compra\"",
              "        )",
              "        , [Participaciones Vendidas de Transacción De Compra] * 'Transacciones'[Precio participación]",
              "    )    ",
              "",
              "RETURN if (coste = 0, BLANK(), coste)"
            ],
            "lineageTag": "abd9c660-e158-4d5d-9677-b14b4021723a"
          },
          {
            "name": "Precio de Venta Total",
            "expression": [
              "",
              "",
              "VAR products = VALUES('Transacciones'[Producto])",
              "VAR dates = VALUES(Calendario[Date])",
              "",
              "VAR revenue = ",
              "CALCULATE(",
              "    SUMX(",
              "        CALCULATETABLE(",
              "            SELECTCOLUMNS('Transacciones', 'Transacciones'[Producto], 'Transacciones'[Total Bruto])                       ",
              "            , products",
              "            , dates            ",
              "        )",
              "        , 'Transacciones'[Total Bruto] * -1 ",
              "    )    ",
              "    , REMOVEFILTERS('Transacciones')",
              "    , 'Transacciones'[Tipo Transacción] = \"Venta\"",
              ")",
              "",
              "RETURN revenue",
              ""
            ],
            "formatString": "0.00",
            "lineageTag": "b3f2b7f3-08c5-4e9f-800c-76e110564481"
          },
          {
            "name": "Beneficio Tras Transacción",
            "expression": [
              "",
              "",
              "VAR last_date = MAX('Transacciones'[Fecha])",
              "VAR products = VALUES('Transacciones'[Producto])",
              "",
              "RETURN ",
              "",
              "CALCULATE(",
              "    [Beneficio Bruto Venta Total]",
              "    , Calendario[Date] <= last_date",
              "    , products",
              ")"
            ],
            "formatString": "0.00",
            "lineageTag": "9e21d318-b805-404f-a7f6-aacdf17dc99c"
          },
          {
            "name": "Coste Participaciones Vendidas Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR products = VALUES('Transacciones'[Producto])",
              "VAR dates = VALUES(Calendario[Date])",
              "",
              "",
              "RETURN ",
              "CALCULATE(",
              "    [Coste Participaciones Vendidas Transaccion]",
              "    , ALL(Transacciones)",
              "    , products ",
              "    , dates",
              ")"
            ],
            "lineageTag": "ede80459-583f-40cd-b03b-4052532aa1a9"
          },
          {
            "name": "Beneficio Bruto Venta Total",
            "expression": [
              "",
              "",
              "VAR beneficio = [Precio de Venta Total] - [Coste Participaciones Vendidas Total]",
              "",
              "RETURN IF(beneficio=0,BLANK(),beneficio)"
            ],
            "formatString": "0.00",
            "lineageTag": "f0b3c4c7-5b2e-4a2f-a77c-6b72a1000659"
          },
          {
            "name": "Beneficio Antes Transacción",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR products = VALUES('Transacciones'[Producto])",
              "VAR last_date = MIN('Transacciones'[Fecha])",
              "",
              "RETURN ",
              "",
              "CALCULATE(",
              "    [Beneficio Bruto Venta Total]",
              "    , Calendario[Date] < last_date",
              "    , Transacciones[Tipo Transacción] IN {\"Compra\",\"Venta\"}",
              "    , REMOVEFILTERS('Transacciones')",
              "    , products",
              ")"
            ],
            "lineageTag": "bac6c5aa-b7fc-40f6-9113-4603a049cd86"
          },
          {
            "name": "Beneficio Bruto Venta Transaccion",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(Transacciones[FIFO Beneficio / Pérdida])",
            "lineageTag": "48dab9c0-036f-4d25-a7d7-5c8c198b23d0"
          },
          {
            "name": "Retenciones Pendientes",
            "expression": [
              "",
              "",
              "SUM('Transacciones'[IRPF Calculado]) - SUM('Transacciones'[Retenido])"
            ],
            "formatString": "0.00",
            "lineageTag": "71a0dc06-6a5a-4456-8064-ac9596e940d2"
          },
          {
            "name": "Beneficio Bruto Total Periodo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "[Beneficio Bruto Venta Transaccion] + [Beneficio Bruto Dividendo]"
            ],
            "lineageTag": "b76497b5-f9e1-4a59-b69a-115c0b296afc"
          },
          {
            "name": "Beneficio Bruto Dividendo",
            "expression": "CALCULATE(SUM(Transacciones[Total Bruto]), Transacciones[Tipo Transacción] = \"Dividendos\")",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "4703907e-48ca-4364-b13a-cf1cfed29a0a"
          },
          {
            "name": "Beneficio Neto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Beneficio Bruto Total Periodo] - 'Medidas IRPF'[IRPF Anual]",
            "lineageTag": "8384ecd4-5ca6-41d1-9547-8008279249e2"
          },
          {
            "name": "Precio Último Transacción",
            "expression": [
              "",
              "IF(HASONEVALUE(Transacciones[Producto]) ,",
              "    CALCULATE(",
              "        SELECTEDVALUE(Transacciones[Precio Participación]), ",
              "        Transacciones[Fecha] = MAX(Transacciones[Fecha]), ",
              "        Transacciones[Hora] = MAX(Transacciones[Hora])    ",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "lineageTag": "942a95b2-d35a-428a-9836-54a93ae1c685"
          }
        ],
        "partitions": [
          {
            "name": "Medidas Transacciones",
            "mode": "import",
            "queryGroup": "Saldo",
            "source": {
              "expression": [
                "let",
                "    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"Columna1\", type text}}),",
                "    #\"Columnas quitadas\" = Table.RemoveColumns(#\"Tipo cambiado\",{\"Columna1\"})",
                "in",
                "    #\"Columnas quitadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "IRPF Ahorro",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7fa4983f-4f59-4f40-a736-54bc0d8336f1",
            "sourceColumn": "Año",
            "summarizeBy": "none"
          },
          {
            "name": "Mínimo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "ce426a05-45a3-449b-be88-a21001574c4e",
            "sourceColumn": "Mínimo",
            "summarizeBy": "none"
          },
          {
            "name": "Máximo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "f14ae6a6-15c9-4cc7-bdf7-b1dcb4603c59",
            "sourceColumn": "Máximo",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "5c44391a-7f3f-4320-8074-995d05cfcc0f",
            "sourceColumn": "Tipo",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "04ca00c9-56eb-421e-94ea-73a2539081f8",
        "partitions": [
          {
            "name": "IRPF Ahorro",
            "mode": "import",
            "queryGroup": "IRPF",
            "source": {
              "expression": [
                "let",
                "    Origen = #\"Origen Data File\",",
                "    T_Saldo_Table = Origen{[Item=\"T_IRPF_Ahorro\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(T_Saldo_Table,{{\"Año\", Int64.Type}, {\"Año Final\", Int64.Type}, {\"Mínimo\", type number}, {\"Máximo\", type number}, {\"Tipo\", Percentage.Type}}),",
                "    #\"Columnas con nombre cambiado\" = Table.RenameColumns(#\"Tipo cambiado\",{{\"Año\", \"Año Actual\"}}),",
                "    #\"Personalizada agregada\" = Table.AddColumn(#\"Columnas con nombre cambiado\", \"Año\", each List.Numbers([Año Actual], (if [Año Final] = null then Date.Year(DateTime.LocalNow()) else [Año Final]) - [Año Actual] + 1)),",
                "    #\"Se expandió Personalizado\" = Table.ExpandListColumn(#\"Personalizada agregada\", \"Año\"),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Se expandió Personalizado\",{{\"Año\", Int64.Type}}),",
                "    #\"Otras columnas quitadas\" = Table.SelectColumns(#\"Tipo cambiado1\",{\"Mínimo\", \"Máximo\", \"Tipo\", \"Año\"}),",
                "    #\"Filas ordenadas\" = Table.Sort(#\"Otras columnas quitadas\",{{\"Año\", Order.Ascending}})",
                "in",
                "    #\"Filas ordenadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas IRPF",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          }
        ],
        "lineageTag": "8f3a51e4-9a1c-4933-885d-ca3ccd2b595f",
        "measures": [
          {
            "name": "IRPF Anual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "    VAR beneficio = [Beneficio IRPF]",
              "",
              "    VAR tramos_ultimo_periodo = CALCULATETABLE(",
              "        SELECTCOLUMNS('IRPF Ahorro', 'IRPF Ahorro'[Mínimo], 'IRPF Ahorro'[Máximo], 'IRPF Ahorro'[Tipo])",
              "        , 'IRPF Ahorro'[Año] = MAX(Transacciones[Año IRPF])",
              "        , 'IRPF Ahorro'[Mínimo] <= beneficio",
              "    )    ",
              "    ",
              "    RETURN         ",
              "        IF(",
              "            beneficio <= 0",
              "            , BLANK()",
              "            , SUMX(",
              "                tramos_ultimo_periodo",
              "                , ",
              "                    VAR minimo = 'IRPF Ahorro'[Mínimo]",
              "                    VAR maximo = 'IRPF Ahorro'[Máximo]",
              "",
              "                    VAR irpf = IF (minimo = 0, MIN(beneficio - minimo, maximo), MIN(MAX(BLANK(), beneficio - minimo), maximo))",
              "",
              "                    RETURN IF (irpf=0, BLANK(), irpf * 'IRPF Ahorro'[Tipo])",
              "            )",
              "        )"
            ],
            "lineageTag": "a7b08e50-4577-4087-bf7a-e4a5fd05428e"
          },
          {
            "name": "Tipo IRPF Anual",
            "expression": [
              "",
              "",
              "VAR fiscal_year = SELECTEDVALUE(Transacciones[Año IRPF])",
              "",
              "RETURN",
              "",
              "    CALCULATE(",
              "        DIVIDE([IRPF Anual], [Beneficio IRPF])",
              "        , Transacciones[Año IRPF] = fiscal_year",
              "    )"
            ],
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "d46c24e9-133e-4295-a1ad-2707722c7281"
          },
          {
            "name": "Beneficio IRPF",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(Transacciones[IRPF - Ganancia / Pérdida Imputable])",
            "lineageTag": "6038c3b8-9c36-4df9-96a8-6e21c0b63051"
          }
        ],
        "partitions": [
          {
            "name": "Medidas IRPF",
            "mode": "import",
            "queryGroup": "IRPF",
            "source": {
              "expression": [
                "let",
                "    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(Origen,{{\"Columna1\", type text}}),",
                "    #\"Columnas quitadas\" = Table.RemoveColumns(#\"Tipo cambiado\",{\"Columna1\"})",
                "in",
                "    #\"Columnas quitadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Transacciones",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Fecha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "86a616c3-5754-453e-8477-954ded922a72",
            "sourceColumn": "Fecha",
            "summarizeBy": "none"
          },
          {
            "name": "Producto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80f7151b-24e8-4357-81fb-091ad039e35c",
            "sourceColumn": "Producto",
            "summarizeBy": "none"
          },
          {
            "name": "Tipo Transacción",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4a60f7c-46df-46f2-b608-15cdc53b02b7",
            "sourceColumn": "Tipo Transacción",
            "summarizeBy": "none"
          },
          {
            "name": "Participaciones",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5ac0577-247e-44ad-a7ce-6f80512e541c",
            "sourceColumn": "Participaciones",
            "summarizeBy": "sum"
          },
          {
            "name": "Retenido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "3b71121f-fe73-4dc0-851c-c0a3c5e68f58",
            "sourceColumn": "Retenido",
            "summarizeBy": "sum"
          },
          {
            "name": "Comisión",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "d231549f-35c6-4457-b10f-a52470732cde",
            "sourceColumn": "Comisión",
            "summarizeBy": "sum"
          },
          {
            "name": "Año IRPF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d545caa2-fedd-438a-9519-c710c492b449",
            "sourceColumn": "Año IRPF",
            "summarizeBy": "none"
          },
          {
            "name": "Año IRPF Fijado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "15b59662-2885-4e33-9f2d-c38ca3b1bd78",
            "sourceColumn": "Año IRPF Fijado",
            "summarizeBy": "none"
          },
          {
            "name": "Precio Participación",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "273f3931-a232-4208-8462-b8ac7216281e",
            "sourceColumn": "Precio Participación",
            "summarizeBy": "sum"
          },
          {
            "name": "Cambio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "8ff5e451-e1fd-49a6-8135-191d51e763bb",
            "sourceColumn": "Cambio",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Bruto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "139098c4-e3bc-4763-8a0a-84e38a48ed63",
            "sourceColumn": "Total Bruto",
            "summarizeBy": "sum"
          },
          {
            "name": "Renta Bruta Obtenida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "21c52de9-6690-4863-8877-72dd3a9aa319",
            "sourceColumn": "Renta Bruta Obtenida",
            "summarizeBy": "sum"
          },
          {
            "name": "Cuenta Producto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19ef5e5d-6dba-4baa-99ae-14492eb5c9c0",
            "sourceColumn": "Cuenta Producto",
            "summarizeBy": "none"
          },
          {
            "name": "Producto Contraparte",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adab4216-f23d-4edd-8dd7-e6b5f16e2e1d",
            "sourceColumn": "Producto Contraparte",
            "summarizeBy": "none"
          },
          {
            "name": "Cuenta Contraparte",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9fb0fd3-ac88-48a5-9ac4-6313711f45fe",
            "sourceColumn": "Cuenta Contraparte",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6545e87d-9278-4379-8861-18fd40954b11",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "IRPF Calculado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "expression": "[IRPF Anual]",
            "lineageTag": "52f32b40-183d-46c3-8ac8-3451be29df89",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "544ae988-d1c9-4c32-b4e8-08d22ab28202",
            "sourceColumn": "Hora",
            "summarizeBy": "none"
          },
          {
            "name": "Precio (Moneda Transacción)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "a9f0d92f-9c50-4674-9bc9-bfdd9f3d8e85",
            "sourceColumn": "Precio (Moneda Transacción)",
            "summarizeBy": "sum"
          },
          {
            "name": "Importe Bruto (Moneda Transacción)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "a2596994-ca4a-49b0-a9ad-448a262d0204",
            "sourceColumn": "Importe Bruto (Moneda Transacción)",
            "summarizeBy": "sum"
          },
          {
            "name": "Retenido (Moneda Transacción)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "ce5dbe70-d11b-4b71-9ccc-0fb392eb3f3c",
            "sourceColumn": "Retenido (Moneda Transacción)",
            "summarizeBy": "sum"
          },
          {
            "name": "Comisión (Moneda Transacción)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "lineageTag": "bc9edcbc-6ddd-4c8d-8dbf-60352407e1e4",
            "sourceColumn": "Comisión (Moneda Transacción)",
            "summarizeBy": "sum"
          },
          {
            "name": "Moneda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f2b702f-c0c1-4b42-9fb1-ddf4f7310cb8",
            "sourceColumn": "Moneda",
            "summarizeBy": "none"
          },
          {
            "name": "Detalle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ef2e46e-de36-4a1d-bfbc-d24c91609dd4",
            "sourceColumn": "Detalle",
            "summarizeBy": "none"
          },
          {
            "name": "Test",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c6b0f786-3c31-4f6a-98a1-c3d7bc195c39",
            "sourceColumn": "Test",
            "summarizeBy": "none"
          },
          {
            "name": "Importe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "02d2c9c9-75e0-467b-85ae-54ee93c0a558",
            "sourceColumn": "Importe",
            "summarizeBy": "sum"
          },
          {
            "name": "Participaciones Acumuladas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "63d16587-c18e-46be-904e-52fb9df4dc27",
            "sourceColumn": "Participaciones Acumuladas",
            "summarizeBy": "sum"
          },
          {
            "name": "Precio Medio Hasta Transacción",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "3b1a9f36-8eeb-40e1-9e58-b0aba44241d6",
            "sourceColumn": "Precio Medio Hasta Transacción",
            "summarizeBy": "sum"
          },
          {
            "name": "FIFO Beneficio / Pérdida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "c8671f87-ca1d-40a1-9fd3-17db2689b499",
            "sourceColumn": "FIFO Beneficio / Pérdida",
            "summarizeBy": "sum"
          },
          {
            "name": "IRPF - Ganancia / Pérdida Imputable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "a982fa5f-74da-43f0-8bc5-61cffa3b341f",
            "sourceColumn": "IRPF - Ganancia / Pérdida Imputable",
            "summarizeBy": "sum"
          },
          {
            "name": "IRPF - Ajuste Diferido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"es-ES\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "73bee529-d67a-4817-a9a3-6adee20388e3",
            "sourceColumn": "IRPF - Ajuste Diferido",
            "summarizeBy": "sum"
          },
          {
            "name": "Fecha/Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "465e905f-fe58-426e-9bac-9a7cb85eae28",
            "sourceColumn": "Fecha/Hora",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variación",
                "defaultHierarchy": {
                  "hierarchy": "Jerarquía de fechas",
                  "table": "LocalDateTable_93f1543f-944f-4988-9370-48e3eab51efc"
                },
                "isDefault": true,
                "relationship": "b40c6ee6-4ff4-4108-9c87-8c3405be1394"
              }
            ]
          }
        ],
        "lineageTag": "c1c9e7c5-0686-4cc6-aa8e-71faa3fa78dc",
        "partitions": [
          {
            "name": "Transacciones",
            "mode": "import",
            "queryGroup": "Saldo",
            "source": {
              "expression": [
                "let    ",
                "    Origen = #\"Transacciones Power Query\",",
                "    #\"Filas ordenadas\" = Table.Sort(Origen,{{\"Fecha\", Order.Ascending}}),",
                "    #\"Tipo cambiado1\" = Table.TransformColumnTypes(#\"Filas ordenadas\",{{\"Fecha\", type text}, {\"Hora\", type text}, {\"Participaciones\", type number}, {\"Precio Participación\", type number}, {\"Precio (Moneda Transacción)\", type number}, {\"Moneda\", type text}, {\"Cambio\", type number}, {\"Importe\", type number}, {\"Importe Bruto (Moneda Transacción)\", type number}, {\"Retenido\", type number}, {\"Retenido (Moneda Transacción)\", type number}, {\"Comisión\", type number}, {\"Comisión (Moneda Transacción)\", type number}, {\"Detalle\", type number}}),",
                "    #\"[Buffer]\" = Table.Buffer(#\"Tipo cambiado1\"),",
                "    #\"[Python] Execute\" = Python.Execute(\"import pandas as pd#(lf)import logging#(lf)from typing import List, Optional # Added for type hinting#(lf)#(lf)# Configuración básica del logger#(lf)logging.basicConfig(filename='H:\\logfile.log', level=logging.ERROR, # Changed to INFO for more detail#(lf)                    format='%(asctime)s - %(name)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s')#(lf)#(lf)# Assuming these are imported correctly from your project structure#(lf)from pyportfolio.transaction_manager import TransactionManager#(lf)from pyportfolio.calculators.fifo_calculator import FIFOCalculator#(lf)from pyportfolio.calculators.irpf_earnings_calculator import (#(lf)    IrpfEarningsCalculator,#(lf)    RESULT_TAXABLE_GAIN_LOSS,#(lf)    RESULT_DEFERRED_ADJUSTMENT#(lf))#(lf)from pyportfolio.columns import FIFO, DATETIME, TRANSACTION_TYPE, TICKER # Added TICKER for grouping context#(lf)#(lf)logger = logging.getLogger(__name__)#(lf)#(lf)# --- Configuration ---#(lf)TEST_COLUMN_NAME = 'Test' #(lf)#(lf)fifo_result_column = FIFO#(lf)irpf_result_columns = [RESULT_TAXABLE_GAIN_LOSS, RESULT_DEFERRED_ADJUSTMENT]#(lf)calculated_columns = [fifo_result_column] + irpf_result_columns#(lf)fifo_result_dtype = 'Float64'#(lf)#(lf)# List to store results from each group processing#(lf)all_results: List[pd.DataFrame] = []#(lf)final_results_df: Optional[pd.DataFrame] = None#(lf)#(lf)# --- Main Processing Logic ---#(lf)try:#(lf)    # --- Input Validation ---#(lf)    if not isinstance(dataset, pd.DataFrame):#(lf)         raise TypeError(\"\"Input 'dataset' is not a pandas DataFrame.\"\")#(lf)    if dataset.empty:#(lf)        logger.warning(\"\"Input dataset is empty. No calculations will be performed.\"\")#(lf)        # Create an empty DataFrame with expected columns based on input if possible#(lf)        expected_cols = dataset.columns.tolist() + calculated_columns#(lf)        final_results_df = pd.DataFrame(columns=list(dict.fromkeys(expected_cols)), index=dataset.index)#(lf)#(lf)    elif TEST_COLUMN_NAME not in dataset.columns:#(lf)        logger.error(f\"\"Mandatory test column '{TEST_COLUMN_NAME}' not found in the input dataset.\"\")#(lf)        # Create an error DataFrame similar to the general exception block#(lf)        original_cols = list(dataset.columns)#(lf)        all_expected_cols = list(dict.fromkeys(original_cols + calculated_columns))#(lf)        final_results_df = pd.DataFrame(index=dataset.index, columns=all_expected_cols)#(lf)        for col in all_expected_cols:#(lf)             if col not in final_results_df.columns: final_results_df[col] = pd.NA#(lf)             elif final_results_df[col].isnull().all(): final_results_df[col] = pd.NA#(lf)        final_results_df['Error'] = f\"\"Missing test column: {TEST_COLUMN_NAME}\"\"#(lf)#(lf)    else:#(lf)        # --- Grouped Processing ---#(lf)        # Group by the test column AND the ticker for calculation context#(lf)        # If calculations are strictly per-test regardless of ticker, remove TICKER here.#(lf)        grouping_columns = [TEST_COLUMN_NAME]#(lf)        if TICKER in dataset.columns:#(lf)            grouping_columns.append(TICKER)#(lf)        else:#(lf)            logger.warning(f\"\"Column '{TICKER}' not found. Grouping only by '{TEST_COLUMN_NAME}'. Calculations might mix tickers within a test.\"\")#(lf)#(lf)        logger.info(f\"\"Starting processing, grouping by: {grouping_columns}\"\")#(lf)        grouped_data = dataset.groupby(grouping_columns, observed=True, group_keys=False) # group_keys=False avoids adding group keys as index#(lf)#(lf)        logger.info(f\"\"Grupos: {grouped_data.size()}\"\")#(lf)        for group_keys, group_df in grouped_data:#(lf)            # Ensure group_keys is a tuple for consistent logging#(lf)            if not isinstance(group_keys, tuple):#(lf)                group_keys = (group_keys,)#(lf)            group_id_str = \"\", \"\".join(map(str, group_keys))#(lf)            logger.info(f\"\"--- Processing Group: {group_id_str} ({len(group_df)} rows) ---\"\")#(lf)#(lf)            try:#(lf)                # --- Calculations for the current group ---#(lf)                # 1. Sort the group data#(lf)                if DATETIME in group_df.columns and TRANSACTION_TYPE in group_df.columns:#(lf)                    dataset_sorted = group_df.sort_values(#(lf)                        by=[DATETIME, TRANSACTION_TYPE],#(lf)                        ascending=[True, True],#(lf)                        key=lambda col: col.map({'buy': 0, 'sell': 1}) if col.name == TRANSACTION_TYPE else col#(lf)                    ).copy() # Use copy to avoid SettingWithCopyWarning on the slice#(lf)                    logger.debug(f\"\"Group {group_id_str}: Sorted by Date and Transaction Type.\"\")#(lf)                else:#(lf)                    logger.warning(f\"\"Group {group_id_str}: Missing '{DATETIME}' or '{TRANSACTION_TYPE}'. Cannot guarantee order.\"\")#(lf)                    dataset_sorted = group_df.copy() # Use copy here as well#(lf)#(lf)                # 2. Initialize TransactionManager for the group#(lf)                tm = TransactionManager(dataset_sorted)#(lf)                logger.debug(f\"\"Group {group_id_str}: Initialized TransactionManager.\"\")#(lf)#(lf)                # 3. Register Calculators (Create new instances for each group for safety)#(lf)                fifo_calculator = FIFOCalculator()#(lf)                tm.register_calculation(#(lf)                    calculator=fifo_calculator,#(lf)                    column=fifo_result_column,#(lf)                    dtype=fifo_result_dtype#(lf)                )#(lf)                logger.debug(f\"\"Group {group_id_str}: Registered FIFOCalculator.\"\")#(lf)#(lf)                irpf_calculator = IrpfEarningsCalculator()#(lf)                tm.register_calculation(#(lf)                    calculator=irpf_calculator#(lf)                )#(lf)                logger.debug(f\"\"Group {group_id_str}: Registered IrpfEarningsCalculator.\"\")#(lf)#(lf)                # 4. Process calculations for the group#(lf)                logger.info(f\"\"Group {group_id_str}: Processing calculations...\"\")#(lf)                tm.process_all()#(lf)                logger.info(f\"\"Group {group_id_str}: Finished processing calculations.\"\")#(lf)#(lf)                # 5. Store the results for this group#(lf)                group_results_df = tm.transactions.copy() # Get the processed data#(lf)                all_results.append(group_results_df)#(lf)                logger.info(f\"\"Group {group_id_str}: Results stored.\"\")#(lf)#(lf)            except Exception as group_e:#(lf)                logger.error(f\"\"Error processing group {group_id_str}: {group_e}\"\", exc_info=True)#(lf)                # Create an error DataFrame for this specific group#(lf)                original_cols = list(group_df.columns)#(lf)                all_expected_cols = list(dict.fromkeys(original_cols + calculated_columns))#(lf)                error_df = pd.DataFrame(index=group_df.index, columns=all_expected_cols)#(lf)                # Fill original columns with original data if possible#(lf)                for col in original_cols:#(lf)                    if col in group_df:#(lf)                        error_df[col] = group_df[col]#(lf)                # Fill calculated columns with NA#(lf)                for col in calculated_columns:#(lf)                     error_df[col] = pd.NA#(lf)                     # Try setting dtype for FIFO column if it exists#(lf)                     if col == fifo_result_column and col in error_df.columns:#(lf)                         try:#(lf)                             error_df[col] = error_df[col].astype(fifo_result_dtype)#(lf)                         except Exception as dtype_e:#(lf)                             logger.warning(f\"\"Could not set dtype for {col} in error df: {dtype_e}\"\")#(lf)#(lf)                error_df['Error'] = f\"\"Error in group {group_id_str}: {str(group_e)}\"\"#(lf)                all_results.append(error_df)#(lf)                logger.info(f\"\"Group {group_id_str}: Created error DataFrame.\"\")#(lf)#(lf)        # --- Combine results after the loop ---#(lf)        if all_results:#(lf)            logger.info(\"\"Concatenating results from all processed groups...\"\")#(lf)            # Concatenate results from all groups#(lf)            final_results_df = pd.concat(all_results)#(lf)            # Restore the original index order from the input dataset#(lf)            final_results_df = final_results_df.reindex(dataset.index)#(lf)            logger.info(\"\"Final results DataFrame created and reindexed successfully.\"\")#(lf)        elif final_results_df is None: # Only if not already handled by empty input case#(lf)             logger.warning(\"\"No groups were processed (e.g., empty groups after filtering). Creating empty DataFrame.\"\")#(lf)             expected_cols = dataset.columns.tolist() + calculated_columns#(lf)             final_results_df = pd.DataFrame(columns=list(dict.fromkeys(expected_cols)), index=dataset.index)#(lf)#(lf)#(lf)except Exception as e:#(lf)    logger.error(f\"\"Critical error during script execution: {e}\"\", exc_info=True)#(lf)    # Create DataFrame vacío con columnas originales (si es posible) + calculadas + error#(lf)    try:#(lf)        original_cols = list(dataset.columns)#(lf)        input_index = dataset.index#(lf)    except Exception as fallback_e:#(lf)        logger.error(f\"\"Could not access original dataset columns/index in fallback error handler: {fallback_e}\"\")#(lf)        original_cols = []#(lf)        input_index = None # Cannot guarantee index preservation#(lf)#(lf)    all_expected_cols = list(dict.fromkeys(original_cols + calculated_columns))#(lf)#(lf)    # Use input_index if available, otherwise, it will be None (default range index)#(lf)    final_results_df = pd.DataFrame(index=input_index, columns=all_expected_cols)#(lf)#(lf)    # Rellenar con NA por si acaso#(lf)    for col in all_expected_cols:#(lf)        if col not in final_results_df.columns: # Should not happen, but safety check#(lf)             final_results_df[col] = pd.NA#(lf)        # Ensure columns exist before trying to fill NA (they should, based on columns=...)#(lf)        elif final_results_df[col].isnull().all():#(lf)             final_results_df[col] = pd.NA#(lf)             # Try setting dtype for FIFO column if it exists#(lf)             if col == fifo_result_column:#(lf)                 try:#(lf)                     final_results_df[col] = final_results_df[col].astype(fifo_result_dtype)#(lf)                 except Exception as dtype_e:#(lf)                     logger.warning(f\"\"Could not set dtype for {col} in final error df: {dtype_e}\"\")#(lf)#(lf)#(lf)    final_results_df['Error'] = f\"\"Critical error: {str(e)}\"\"#(lf)    logger.info(\"\"Created final error DataFrame due to critical failure.\"\")#(lf)#(lf)#(lf)# --- Final Assignment ---#(lf)result = final_results_df if final_results_df is not None else pd.DataFrame()#(lf)\",[dataset=#\"[Buffer]\"]),",
                "    #\"[Python] Result\" = #\"[Python] Execute\"{[Name=\"result\"]}[Value],",
                "    #\"[Values][Replace] Treat .\" = Table.TransformColumns(",
                "    #\"[Python] Result\",",
                "    {",
                "        {\"Participaciones\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Precio Participación\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Precio (Moneda Transacción)\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Cambio\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Importe\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Importe Bruto (Moneda Transacción)\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Retenido\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Retenido (Moneda Transacción)\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Comisión\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Comisión (Moneda Transacción)\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Total Bruto\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Participaciones Acumuladas\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Precio Medio Hasta Transacción\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Renta Bruta Obtenida\", each Text.Replace(_, \".\", \",\")},",
                "        {\"FIFO Beneficio / Pérdida\", each Text.Replace(_, \".\", \",\")},",
                "        {\"IRPF - Ganancia / Pérdida Imputable\", each Text.Replace(_, \".\", \",\")},",
                "        {\"IRPF - Ajuste Diferido\", each Text.Replace(_, \".\", \",\")},",
                "        {\"Año IRPF\", each Text.Replace(_, \".\", \",\")}",
                "    }",
                "),",
                "    #\"[Type] Update\" = Table.TransformColumnTypes(#\"[Values][Replace] Treat .\",{{\"Fecha\", type date}, {\"Hora\", type time}, {\"Participaciones\", type number}, {\"Precio Participación\", Currency.Type}, {\"Precio (Moneda Transacción)\", Currency.Type}, {\"Cambio\", type number}, {\"Importe\", Currency.Type}, {\"Importe Bruto (Moneda Transacción)\", Currency.Type}, {\"Retenido\", Currency.Type}, {\"Retenido (Moneda Transacción)\", Currency.Type}, {\"Año IRPF\", Int64.Type}, {\"Comisión\", Currency.Type}, {\"Comisión (Moneda Transacción)\", Currency.Type}, {\"Total Bruto\", Currency.Type}, {\"Año IRPF Fijado\", type logical}, {\"ID\", Int64.Type}, {\"Participaciones Acumuladas\", type number}, {\"Precio Medio Hasta Transacción\", type number}, {\"Renta Bruta Obtenida\", Currency.Type}, {\"FIFO Beneficio / Pérdida\", Currency.Type}, {\"IRPF - Ganancia / Pérdida Imputable\", Currency.Type}, {\"IRPF - Ajuste Diferido\", Currency.Type}, {\"Fecha/Hora\", type datetime}})",
                "in",
                "    #\"[Type] Update\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Años Fiscales",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f74170c1ada245ad8c8af3a0fbc0acc0"
          }
        ],
        "columns": [
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "575b102f-886d-4a42-9d3a-ae4c1624dfbd",
            "sourceColumn": "IRPF Ahorro[Año]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "bdca8db4-4a09-4b1b-afb2-e18d359bbc3f",
        "partitions": [
          {
            "name": "Años Fiscales",
            "mode": "import",
            "source": {
              "expression": "VALUES('IRPF Ahorro'[Año])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Test Genérico",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Actual",
              "expression": [
                "",
                "",
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    KEEPFILTERS(",
                "        IF(",
                "            ISBLANK(SELECTEDVALUE('Test Data'[mes])),",
                "            TRUE(),",
                "            Calendario[Mes (Num.)] = VALUE(SELECTEDVALUE('Test Data'[mes]))",
                "        )",
                "    ),",
                "    KEEPFILTERS(",
                "        IF(",
                "            ISBLANK(SELECTEDVALUE('Test Data'[año])),",
                "            TRUE(),",
                "            Calendario[Año] = VALUE(SELECTEDVALUE('Test Data'[año]))",
                "        )",
                "    ),",
                "    KEEPFILTERS(",
                "        IF(",
                "            ISBLANK(SELECTEDVALUE('Test Data'[año IRPF])),",
                "            TRUE(),",
                "            'Años Fiscales'[Año] = VALUE(SELECTEDVALUE('Test Data'[año IRPF]))",
                "        )",
                "    )",
                ")",
                "",
                "/*CALCULATE(",
                "    SELECTEDMEASURE()",
                "    , KEEPFILTERS(",
                "        FILTER(Calendario, ",
                "            IF(",
                "                ISBLANK(SELECTEDVALUE('Test Data'[mes])), TRUE(), Calendario[Mes (Num.)] = VALUE(SELECTEDVALUE('Test Data'[mes]))",
                "            )",
                "            &&             ",
                "            IF(",
                "                ISBLANK(SELECTEDVALUE('Test Data'[año])), TRUE(), Calendario[Año] = VALUE(SELECTEDVALUE('Test Data'[año]))",
                "            )",
                "        )",
                "    ) ",
                "    , KEEPFILTERS(",
                "        FILTER('Años Fiscales', ",
                "            IF(",
                "                ISBLANK(SELECTEDVALUE('Test Data'[año IRPF])), TRUE(), TRUE() // 'Años Fiscales'[Año] = VALUE(SELECTEDVALUE('Test Data'[año IRPF]))",
                "            )",
                "        )",
                "    )",
                ")*/"
              ],
              "formatStringDefinition": {
                "expression": "\"\""
              }
            },
            {
              "name": "Esperado",
              "expression": [
                "",
                "",
                "IF(",
                "    SELECTEDMEASURENAME() = \"Test - Número Errores\", ",
                "    CALCULATE(SELECTEDMEASURE(), REMOVEFILTERS('Test Genérico'), 'Test Genérico'[Test Genérico] = \"Error\"), ",
                "    IFERROR(VALUE(SELECTEDVALUE('Test Data'[Valor Esperado])), SELECTEDVALUE('Test Data'[Valor Esperado]))",
                ")"
              ],
              "formatStringDefinition": {
                "expression": "\"\""
              }
            },
            {
              "name": "Error",
              "expression": [
                "",
                "",
                "VAR actual = ",
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    KEEPFILTERS(",
                "        IF(",
                "            ISBLANK(SELECTEDVALUE('Test Data'[mes])),",
                "            TRUE(),",
                "            Calendario[Mes (Num.)] = VALUE(SELECTEDVALUE('Test Data'[mes]))",
                "        )",
                "    ),",
                "    KEEPFILTERS(",
                "        IF(",
                "            ISBLANK(SELECTEDVALUE('Test Data'[año])),",
                "            TRUE(),",
                "            Calendario[Año] = VALUE(SELECTEDVALUE('Test Data'[año]))",
                "        )",
                "    ),",
                "    KEEPFILTERS(",
                "        IF(",
                "            ISBLANK(SELECTEDVALUE('Test Data'[año IRPF])),",
                "            TRUE(),",
                "            'Años Fiscales'[Año] = VALUE(SELECTEDVALUE('Test Data'[año IRPF]))",
                "        )",
                "    )",
                ")",
                "",
                "VAR esperado = IFERROR(VALUE(SELECTEDVALUE('Test Data'[Valor Esperado])), SELECTEDVALUE('Test Data'[Valor Esperado]))",
                "",
                "RETURN ",
                "IF (",
                "    OR(actual = esperado , AND(ISBLANK(actual), ISBLANK(esperado)))",
                "    ,0",
                "    ,1",
                ")"
              ]
            }
          ]
        },
        "columns": [
          {
            "name": "Test Genérico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6df3cd6-0c31-4c66-9d25-ba416b937e0b",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "57efed6d-0d1c-4c7e-abe4-56b49cf6b7a0",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "description": [
          "Test Saldo / Inversiones básico.",
          "",
          "Contexto prueba: Febrero 2000 "
        ],
        "lineageTag": "6752251f-d3de-4780-aa6e-ba71f6a8d2f1",
        "partitions": [
          {
            "name": "Test Genérico",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Test",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8da5445724bc4ea5aed1d160fc5f002a"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4424ad8e-526d-4d32-9602-573283ca39a1",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "21f1dadb-4d7a-4526-b93d-83e230fcb845",
        "measures": [
          {
            "name": "Test - Medida Seleccionada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "SWITCH(",
              "    SELECTEDVALUE('Test Data'[Medida])",
              "    , \"Saldo Fecha Inicio\", [Saldo Fecha Inicio]",
              "    , \"Saldo Último\", [Saldo Último]",
              "    , \"Gastos no Computados Periodo\", [Gastos no Computados Periodo]",
              "    , \"Beneficio Inversión\", [Beneficio Inversión]",
              "    , \"Beneficio IRPF\", [Beneficio IRPF]",
              "    , \"Movimientos Totales Periodo\", [Movimientos Totales Periodo]",
              "    , \"Beneficio Bruto Total Periodo\", [Beneficio Bruto Total Periodo]",
              "    , \"IRPF Anual\", [IRPF Anual]   ",
              "    , \"Tipo IRPF Anual\", [Tipo IRPF Anual]",
              "    , \"Ingresos Inversión\", [Ingresos Inversion]",
              "    , \"CONFIGURAR MEDIDA\"",
              ")",
              ""
            ],
            "lineageTag": "fd9278ab-02ea-4140-9799-f46f3b6af606"
          },
          {
            "name": "Test - Número Errores",
            "expression": [
              "",
              "",
              "SUMX(",
              "    SUMMARIZE('Test Data', 'Test Data'[Medida],'Test Data'[Prueba]), ",
              "    CALCULATE(",
              "        [Test - Medida Seleccionada]",
              "        , 'Test Genérico'[Test Genérico] = \"Error\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "897aa625-ca38-44b6-9c3a-38cbf0a8d2d7"
          },
          {
            "name": "Test - Passed Rate",
            "expression": "DIVIDE(COUNTROWS('Test Data') - Test[Test - Número Errores], COUNTROWS('Test Data'))",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "d152038e-7dfc-4454-ba5f-ab06f4376394"
          },
          {
            "name": "Texto - Errores",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "FORMAT(Test[Test - Número Errores], \"#,0\") & \"/\" & FORMAT(COUNTROWS('Test Data'),\"#,0\")",
            "lineageTag": "2cacabf8-fd7b-4fbd-a63e-2deaa18eb84a"
          }
        ],
        "partitions": [
          {
            "name": "Test",
            "mode": "import",
            "source": {
              "expression": "{\"\"}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Test Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegación"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Medida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba75b998-921b-4a1e-8036-e580edf6dfb7",
            "sourceColumn": "Medida",
            "summarizeBy": "none"
          },
          {
            "name": "Test",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fabe67b9-393c-4698-8721-7fbd57689f08",
            "sourceColumn": "Test",
            "summarizeBy": "none"
          },
          {
            "name": "Prueba",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92934524-46f0-4dae-81c9-93ec1a38c24d",
            "sourceColumn": "Prueba",
            "summarizeBy": "none"
          },
          {
            "name": "Descripción",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "979c04f1-b76c-4eea-b3ae-5d98e555b6a8",
            "sourceColumn": "Descripción",
            "summarizeBy": "none"
          },
          {
            "name": "Valor Esperado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1af90a23-7bd1-40c5-949f-15dad93c6281",
            "sourceColumn": "Valor Esperado",
            "summarizeBy": "none"
          },
          {
            "name": "año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "22ce8eb0-42bd-46d8-8632-63f6084dc034",
            "sourceColumn": "año",
            "summarizeBy": "sum"
          },
          {
            "name": "mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a172d166-e884-4427-9a3d-b393caff349d",
            "sourceColumn": "mes",
            "summarizeBy": "sum"
          },
          {
            "name": "año IRPF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "865e0033-8c21-49a2-aa04-c73300222612",
            "sourceColumn": "año IRPF",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b4022ae7-63a8-4ebd-a1c0-0f326d7e47b7",
        "partitions": [
          {
            "name": "Test Data",
            "mode": "import",
            "queryGroup": "Test",
            "source": {
              "expression": [
                "let",
                "    Origen = #\"Origen Data File\",    ",
                "    T_Saldo_Table = Origen{[Item=\"T_TestData\",Kind=\"Table\"]}[Data],",
                "",
                "    resultado = if List.Contains(List.Transform(Origen[Name], Text.Lower), \"t_testdata\") then ",
                "",
                "        let        ",
                "            #\"Tipo cambiado\" = Table.TransformColumnTypes(T_Saldo_Table,{{\"Medida\", type text}, {\"Prueba\", type text}, {\"Descripción\", type text}}),",
                "            #\"JSON analizado\" = Table.TransformColumns(#\"Tipo cambiado\",{{\"Parámetros\", Json.Document}}),",
                "            #\"Se expandió Parámetros\" = Table.ExpandRecordColumn(#\"JSON analizado\", \"Parámetros\", {\"año\", \"mes\", \"año IRPF\"}, {\"año\", \"mes\", \"año IRPF\"}),",
                "            #\"test_data\" = Table.TransformColumnTypes(#\"Se expandió Parámetros\",{{\"año\", Int64.Type}, {\"mes\", Int64.Type}, {\"año IRPF\", Int64.Type}, {\"Valor Esperado\", type text}, {\"Test\", type text}})",
                "",
                "        in ",
                "            #\"test_data\"",
                "",
                "    else",
                "        #table({\"Medida\",\"Test\", \"Prueba\",\"Descripción\",\"Valor Esperado\",\"Parámetros\"}, {}),",
                "    #\"Tipo cambiado\" = Table.TransformColumnTypes(resultado,{{\"Medida\", type text}, {\"Test\", type text}, {\"Prueba\", type text}, {\"Descripción\", type text}, {\"Valor Esperado\", type text}})",
                "in",
                "    #\"Tipo cambiado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_c89e3af7-f9f4-492b-8e82-a0927b77cae5",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3a40b32e-2c2f-4b79-91b0-46c1ff7fde38",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "561857ad-1f98-4ce8-ada9-3a125dafe232",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "11f8bf9d-1bc6-4bec-bd08-501f5b2d34bb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ab5e0bf3-e801-46d4-b1fa-c2d252dfec91",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dbba1cfd-f522-4619-bc8e-51ea5a4ee545",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "f1343d01-6d19-4e09-a3ea-34174731c45d",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad8bf253-2d04-4cd2-aa0c-a20dec48a534",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "5d20b4c9-e4c1-4fd2-99f5-90fbf3008409",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "6dcf4591-cc97-4afb-9714-852d02d9e040",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "3e967748-0183-4e29-a29b-02754f08f44a",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "6606986f-cdbf-4e15-b0b3-175500f4dad9",
                "ordinal": 3
              }
            ],
            "lineageTag": "822e3f11-fcc4-42ee-8573-fc2f77e28095"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "267a983e-64a2-4a5c-9ecd-d399d965bdfd",
        "partitions": [
          {
            "name": "DateTableTemplate_c89e3af7-f9f4-492b-8e82-a0927b77cae5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_93f1543f-944f-4988-9370-48e3eab51efc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "51cb3e80-4d16-47e3-9902-f078e3a9a7b0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1d88c91d-5141-4a54-be20-1e1779e177fe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f6e764a5-61e3-4c21-adb7-4f7533286dcd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f9249ce1-ea31-4702-b007-4dec218ad3a5",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "80489f0e-4d2c-4de6-b300-b3f0c9c7804b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "c7c9e917-e042-4f98-a521-d08e8eb6f235",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9df9c7b6-44b6-4057-bc3b-93ac7281ef50",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "ddae4d63-9388-41e9-ad28-a69d7558a294",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "f2234e0c-6ecf-4ae8-9c62-e18917076d0d",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "0b4c944e-ea31-48b7-a8ea-64ac1961fd93",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "f5dd14c4-e117-4138-9290-5a102c0e7671",
                "ordinal": 3
              }
            ],
            "lineageTag": "bb247e88-3e46-45a7-8162-4112bead20f7"
          }
        ],
        "isHidden": true,
        "lineageTag": "62e519de-bfad-4076-8032-42a1c8f38a53",
        "partitions": [
          {
            "name": "LocalDateTable_93f1543f-944f-4988-9370-48e3eab51efc",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Transacciones'[Fecha/Hora])), 1, 1), Date(Year(MAX('Transacciones'[Fecha/Hora])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b9da2914-fd53-4f32-b21c-39fa4c9bbfb1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "91ece43d-c383-437f-8c73-6cf02373d6d3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Año",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "86ecf636-d452-441c-acf4-c011cf519955",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroMes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "64eaec31-dc8d-4212-8903-49609a3ebeac",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "52f3fe9d-ea39-4d10-9c57-13f549ded0a1",
            "sortByColumn": "NroMes",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NroTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NroMes] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5922a4a5-4496-4989-b056-280316f35817",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [NroTrimestre]",
            "isHidden": true,
            "lineageTag": "e6871f38-3de9-4720-bc87-53ca5f13d4c6",
            "sortByColumn": "NroTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Día",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "20fc667d-2c8d-4b34-8772-5786ed60fee1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Jerarquía de fechas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Año",
                "column": "Año",
                "lineageTag": "b2401797-1ef3-414c-98d1-e42b7aac5d75",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "6486a772-4178-4700-a6cc-633a2db58142",
                "ordinal": 1
              },
              {
                "name": "Mes",
                "column": "Mes",
                "lineageTag": "288b2e10-8581-434c-b79b-be273853c0c1",
                "ordinal": 2
              },
              {
                "name": "Día",
                "column": "Día",
                "lineageTag": "4123ac18-8665-415d-890a-b1b341c37a3a",
                "ordinal": 3
              }
            ],
            "lineageTag": "17cf9bfe-425f-4970-8d8d-a5a3cf2151c3"
          }
        ],
        "isHidden": true,
        "lineageTag": "934a6adf-b5d9-41f0-94ee-a497c231794f",
        "partitions": [
          {
            "name": "LocalDateTable_b9da2914-fd53-4f32-b21c-39fa4c9bbfb1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dividendos'[Fecha/Hora])), 1, 1), Date(Year(MAX('Dividendos'[Fecha/Hora])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}