table IRPF
	lineageTag: d656388b-c402-4d9c-8953-455885b907b4

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 02d65980-61da-40f5-86ed-d427b5f2e534
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column GPP
		dataType: double
		lineageTag: 2df98632-e2fa-4985-ab83-035c8c691fdb
		summarizeBy: sum
		sourceColumn: GPP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RCM
		dataType: double
		lineageTag: 08995cc0-6dd4-4cee-b87f-3155ebcd068f
		summarizeBy: sum
		sourceColumn: RCM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GPP Loss Available'
		dataType: double
		lineageTag: 9f100a2c-bd2a-4f04-9250-79727a58af5a
		summarizeBy: sum
		sourceColumn: GPP Loss Available

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RCM Loss Available'
		dataType: double
		lineageTag: e0c60e3d-c349-4ccc-9739-824f281b276c
		summarizeBy: sum
		sourceColumn: RCM Loss Available

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GPP Post Compensation'
		dataType: double
		lineageTag: 5cef55d4-92a0-478b-8dcc-d89fc5c86a8d
		summarizeBy: sum
		sourceColumn: GPP Post Compensation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RCM Post Compensation'
		dataType: double
		lineageTag: 7148a53c-e8fc-4057-80f1-fcf57d2ba6ef
		summarizeBy: sum
		sourceColumn: RCM Post Compensation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GPP Taxable Base'
		dataType: double
		lineageTag: 4784c74f-87c1-4b2d-9978-41d91177a7b2
		summarizeBy: sum
		sourceColumn: GPP Taxable Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RCM Taxable Base'
		dataType: double
		lineageTag: 1e106542-0ccd-41f2-a696-a6054bc5e56e
		summarizeBy: sum
		sourceColumn: RCM Taxable Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Taxable Base'
		dataType: double
		lineageTag: bf1a86fc-53ae-4fd3-944e-6b2ff956ce5a
		summarizeBy: sum
		sourceColumn: Total Taxable Base

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GPP Loss Carried Forward'
		dataType: double
		lineageTag: e9a33cca-95e1-4591-9ab5-28d4c6066486
		summarizeBy: sum
		sourceColumn: GPP Loss Carried Forward

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RCM Loss Carried Forward'
		dataType: double
		lineageTag: d8c3aa66-4e85-46f5-8c4b-83a720851a54
		summarizeBy: sum
		sourceColumn: RCM Loss Carried Forward

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Test
		dataType: string
		lineageTag: 0d13dd40-d348-4de1-9099-40e114ee15a6
		summarizeBy: none
		sourceColumn: Test

		annotation SummarizationSetBy = Automatic

	partition IRPF = m
		mode: import
		queryGroup: IRPF
		source = ```
				let    
				    Origen = #"Transacciones Power Query",
				    #"Filas ordenadas" = Table.Sort(Origen,{{"Fecha", Order.Ascending}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas ordenadas",{{"Fecha", type text}, {"Hora", type text}}),
				    #"[Buffer]" = Table.Buffer(#"Tipo cambiado"),
				    #"[Python] Execute" = Python.Execute("import pyportfolio.scripts.powerquery.pq_get_irpf_report as script#(lf)#(lf)import logging#(lf)#(lf)logger = logging.getLogger(__name__)#(lf)#(lf)logging.basicConfig(filename='C:\\Users\\Public\\Log\\logfile.log', level=logging.WARNING, # Changed to INFO for more detail#(lf)                    format='%(asctime)s - %(name)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s')#(lf)#(lf)result = script.pq_get_irpf_report(dataset)#(lf)#(lf)logger.debug(f""Power Query Actual columns: {result.columns.tolist()}"")#(lf)#(lf)result",[dataset=#"[Buffer]"]),
				    result = #"[Python] Execute"{[Name="result"]}[Value],
				    #"Subs . by ," = Table.TransformColumns(
				        result, 
				        {
				            {"GPP", each Text.Replace(_, ".", ",")},
				            {"RCM", each Text.Replace(_, ".", ",")},
				            {"GPP Loss Available", each Text.Replace(_, ".", ",")},
				            {"RCM Loss Available", each Text.Replace(_, ".", ",")},
				            {"GPP Post Compensation", each Text.Replace(_, ".", ",")},
				            {"RCM Post Compensation", each Text.Replace(_, ".", ",")},
				            {"GPP Taxable Base", each Text.Replace(_, ".", ",")}, 
				            {"RCM Taxable Base", each Text.Replace(_, ".", ",")},
				            {"Total Taxable Base", each Text.Replace(_, ".", ",")},
				            {"GPP Loss Carried Forward", each Text.Replace(_, ".", ",")},
				            {"RCM Loss Carried Forward", each Text.Replace(_, ".", ",")}
				        }
				    ),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Subs . by ,",{{"Year", Int64.Type}, {"GPP", type number}, {"RCM", type number}, {"GPP Loss Available", type number}, {"RCM Loss Available", type number}, {"GPP Post Compensation", type number}, {"RCM Post Compensation", type number}, {"GPP Taxable Base", type number}, {"RCM Taxable Base", type number}, {"Total Taxable Base", type number}, {"GPP Loss Carried Forward", type number}, {"RCM Loss Carried Forward", type number}})
				in
				    #"Tipo cambiado1"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

