table IRPF
	lineageTag: d656388b-c402-4d9c-8953-455885b907b4

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 02d65980-61da-40f5-86ed-d427b5f2e534
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column RCM
		dataType: double
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		lineageTag: 08995cc0-6dd4-4cee-b87f-3155ebcd068f
		summarizeBy: sum
		sourceColumn: RCM

		annotation SummarizationSetBy = Automatic

	column 'Pérdidas GPP Compensables'
		dataType: double
		lineageTag: 9f100a2c-bd2a-4f04-9250-79727a58af5a
		summarizeBy: sum
		sourceColumn: Pérdidas GPP Compensables

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pérdidas RCM Compensables'
		dataType: double
		lineageTag: e0c60e3d-c349-4ccc-9739-824f281b276c
		summarizeBy: sum
		sourceColumn: Pérdidas RCM Compensables

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GPP Tras Compensación'
		dataType: double
		lineageTag: 5cef55d4-92a0-478b-8dcc-d89fc5c86a8d
		summarizeBy: sum
		sourceColumn: GPP Tras Compensación

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'RCM Tras Compensación'
		dataType: double
		lineageTag: 7148a53c-e8fc-4057-80f1-fcf57d2ba6ef
		summarizeBy: sum
		sourceColumn: RCM Tras Compensación

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Base de GPP
	column 'Base Imponible GPP'
		dataType: double
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		lineageTag: 4784c74f-87c1-4b2d-9978-41d91177a7b2
		summarizeBy: sum
		sourceColumn: Base Imponible GPP

		annotation SummarizationSetBy = Automatic

	column 'Base Imponible RCM'
		dataType: double
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		lineageTag: 1e106542-0ccd-41f2-a696-a6054bc5e56e
		summarizeBy: sum
		sourceColumn: Base Imponible RCM

		annotation SummarizationSetBy = Automatic

	column 'Base Imponible Total'
		dataType: double
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		lineageTag: bf1a86fc-53ae-4fd3-944e-6b2ff956ce5a
		summarizeBy: sum
		sourceColumn: Base Imponible Total

		annotation SummarizationSetBy = Automatic

	column 'Pérdidas GPP a Compensar Futuro'
		dataType: double
		lineageTag: e9a33cca-95e1-4591-9ab5-28d4c6066486
		summarizeBy: sum
		sourceColumn: Pérdidas GPP a Compensar Futuro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pérdidas RCM a Compensar Futuro'
		dataType: double
		lineageTag: d8c3aa66-4e85-46f5-8c4b-83a720851a54
		summarizeBy: sum
		sourceColumn: Pérdidas RCM a Compensar Futuro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Test
		dataType: string
		lineageTag: 0d13dd40-d348-4de1-9099-40e114ee15a6
		summarizeBy: none
		sourceColumn: Test

		annotation SummarizationSetBy = Automatic

	column 'GPP Total'
		dataType: double
		lineageTag: 333d1b70-5cb9-48bf-8062-5a7273c58187
		summarizeBy: sum
		sourceColumn: GPP Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GPP Disponible'
		dataType: double
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		lineageTag: 66b0c835-52fe-424e-99dc-122e402b62b7
		summarizeBy: sum
		sourceColumn: GPP Disponible

		annotation SummarizationSetBy = Automatic

	partition IRPF = m
		mode: import
		queryGroup: IRPF
		source = ```
				let    
				    Origen = #"Transacciones Power Query",
				    #"Filas ordenadas" = Table.Sort(Origen,{{"Fecha", Order.Ascending}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas ordenadas",{{"Fecha", type text}, {"Hora", type text}}),
				    #"[Buffer]" = Table.Buffer(#"Tipo cambiado"),
				    #"[Python] Execute" = Python.Execute("import pyportfolio.scripts.powerquery.pq_get_irpf_report as script#(lf)#(lf)import logging#(lf)#(lf)logger = logging.getLogger(__name__)#(lf)#(lf)logging.basicConfig(filename='C:\\Users\\Public\\Log\\logfile.log', level=logging.WARNING, # Changed to INFO for more detail#(lf)                    format='%(asctime)s - %(name)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s')#(lf)#(lf)result = script.pq_get_irpf_report(dataset)#(lf)#(lf)logger.debug(f""Power Query Actual columns: {result.columns.tolist()}"")#(lf)#(lf)result",[dataset=#"[Buffer]"]),
				    result = #"[Python] Execute"{[Name="result"]}[Value],
				    #"Subs . by ," = Table.TransformColumns(
				        result, 
				        {   {"GPP Total", each Text.Replace(_, ".", ",")},
				            {"GPP Allowable", each Text.Replace(_, ".", ",")},
				            {"RCM", each Text.Replace(_, ".", ",")},
				            {"GPP Loss Available", each Text.Replace(_, ".", ",")},
				            {"RCM Loss Available", each Text.Replace(_, ".", ",")},
				            {"GPP Post Compensation", each Text.Replace(_, ".", ",")},
				            {"RCM Post Compensation", each Text.Replace(_, ".", ",")},
				            {"GPP Taxable Base", each Text.Replace(_, ".", ",")}, 
				            {"RCM Taxable Base", each Text.Replace(_, ".", ",")},
				            {"Total Taxable Base", each Text.Replace(_, ".", ",")},
				            {"GPP Loss Carried Forward", each Text.Replace(_, ".", ",")},
				            {"RCM Loss Carried Forward", each Text.Replace(_, ".", ",")}
				        }
				    ),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Subs . by ,",{{"Year", Int64.Type}, {"GPP Total", type number}, {"GPP Allowable", type number}, {"RCM", type number}, {"GPP Loss Available", type number}, {"RCM Loss Available", type number}, {"GPP Post Compensation", type number}, {"RCM Post Compensation", type number}, {"GPP Taxable Base", type number}, {"RCM Taxable Base", type number}, {"Total Taxable Base", type number}, {"GPP Loss Carried Forward", type number}, {"RCM Loss Carried Forward", type number}}),
				    Personalizado1 = Table.RenameColumns(#"Tipo cambiado1", {
				    {"Year", "Año"},
				    {"GPP Allowable", "GPP Disponible"},
				    {"RCM", "RCM"},
				    {"GPP Loss Available", "Pérdidas GPP Compensables"},
				    {"RCM Loss Available", "Pérdidas RCM Compensables"},
				    {"GPP Post Compensation", "GPP Tras Compensación"},
				    {"RCM Post Compensation", "RCM Tras Compensación"},
				    {"GPP Taxable Base", "Base Imponible GPP"},
				    {"RCM Taxable Base", "Base Imponible RCM"},
				    {"Total Taxable Base", "Base Imponible Total"},
				    {"GPP Loss Carried Forward", "Pérdidas GPP a Compensar Futuro"},
				    {"RCM Loss Carried Forward", "Pérdidas RCM a Compensar Futuro"}
				})
				in
				    Personalizado1
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Exception

