table 'IRPF Ahorro'
	lineageTag: 04ca00c9-56eb-421e-94ea-73a2539081f8

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 7fa4983f-4f59-4f40-a736-54bc0d8336f1
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mínimo
		dataType: double
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: ce426a05-45a3-449b-be88-a21001574c4e
		summarizeBy: none
		sourceColumn: Mínimo

		annotation SummarizationSetBy = User

	column Máximo
		dataType: double
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: f14ae6a6-15c9-4cc7-bdf7-b1dcb4603c59
		summarizeBy: none
		sourceColumn: Máximo

		annotation SummarizationSetBy = User

	column Tipo
		dataType: double
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 5c44391a-7f3f-4320-8074-995d05cfcc0f
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = User

	partition 'IRPF Ahorro' = m
		mode: import
		queryGroup: IRPF
		source =
				let
				    Origen = #"Origen Data File",
				    T_Saldo_Table = Origen{[Item="T_IRPF_Ahorro",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(T_Saldo_Table,{{"Año", Int64.Type}, {"Año Final", Int64.Type}, {"Mínimo", type number}, {"Máximo", type number}, {"Tipo", Percentage.Type}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"Año", "Año Actual"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "Año", each List.Numbers([Año Actual], (if [Año Final] = null then Date.Year(DateTime.LocalNow()) else [Año Final]) - [Año Actual] + 1)),
				    #"Se expandió Personalizado" = Table.ExpandListColumn(#"Personalizada agregada", "Año"),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Se expandió Personalizado",{{"Año", Int64.Type}}),
				    #"Otras columnas quitadas" = Table.SelectColumns(#"Tipo cambiado1",{"Mínimo", "Máximo", "Tipo", "Año"}),
				    #"Filas ordenadas" = Table.Sort(#"Otras columnas quitadas",{{"Año", Order.Ascending}})
				in
				    #"Filas ordenadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Exception

