table 'Medidas IRPF'
	lineageTag: 8f3a51e4-9a1c-4933-885d-ca3ccd2b595f

	measure 'IRPF Anual' = ```
			
			
			    VAR beneficio = [Ganancias / Pérdidas Patrimoniales]
			
			    VAR tramos_ultimo_periodo = CALCULATETABLE(
			        SELECTCOLUMNS('IRPF Ahorro', 'IRPF Ahorro'[Mínimo], 'IRPF Ahorro'[Máximo], 'IRPF Ahorro'[Tipo])
			        , 'IRPF Ahorro'[Año] = MAX(Transacciones[Año IRPF])
			        , 'IRPF Ahorro'[Mínimo] <= beneficio
			    )    
			    
			    RETURN         
			        IF(
			            beneficio <= 0
			            , BLANK()
			            , SUMX(
			                tramos_ultimo_periodo
			                , 
			                    VAR minimo = 'IRPF Ahorro'[Mínimo]
			                    VAR maximo = 'IRPF Ahorro'[Máximo]
			
			                    VAR irpf = IF (minimo = 0, MIN(beneficio - minimo, maximo), MIN(MAX(BLANK(), beneficio - minimo), maximo))
			
			                    RETURN IF (irpf=0, BLANK(), irpf * 'IRPF Ahorro'[Tipo])
			            )
			        )
			```
		lineageTag: a7b08e50-4577-4087-bf7a-e4a5fd05428e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tipo IRPF Anual' = ```
			
			
			VAR fiscal_year = SELECTEDVALUE(Transacciones[Año IRPF])
			
			RETURN   
			    CALCULATE(
			            DIVIDE([IRPF Anual], [Ganancias / Pérdidas Patrimoniales])
			            , Transacciones[Año IRPF] = fiscal_year
			    )        
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d46c24e9-133e-4295-a1ad-2707722c7281

	measure 'Ganancias / Pérdidas Patrimoniales' = SUM(Transacciones[Ganancias / Pérdidas Patrimoniales (GPP)])
		lineageTag: 6038c3b8-9c36-4df9-96a8-6e21c0b63051

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Presentación - Tipo IRPF Anual' = COALESCE([Tipo IRPF Anual], "Seleccione Año")
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7b3e8605-d345-4583-b489-42ef3a2b5ec9

	measure 'Rendimientos Capital Mobiliario' = SUM(Transacciones[Rendimientos Capital Mobiliario])
		lineageTag: 7052e4fd-3e0d-4afe-af01-bf158bfe263d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Medidas IRPF' = m
		mode: import
		queryGroup: IRPF
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

