table 'Medidas IRPF'
	lineageTag: 8f3a51e4-9a1c-4933-885d-ca3ccd2b595f

	measure 'IRPF Anual Ahorro' = ```
			
			
			    VAR beneficio = [Base Imponible del Ahorro]
			
			    VAR tramos_ultimo_periodo = CALCULATETABLE(
			        SELECTCOLUMNS('IRPF Ahorro', 'IRPF Ahorro'[Mínimo], 'IRPF Ahorro'[Máximo], 'IRPF Ahorro'[Tipo])
			        , 'IRPF Ahorro'[Año] = MAX(Transacciones[Año IRPF])
			        , 'IRPF Ahorro'[Mínimo] <= beneficio
			    )    
			    
			    RETURN         
			        IF(
			            beneficio <= 0
			            , BLANK()
			            , SUMX(
			                tramos_ultimo_periodo
			                , 
			                    VAR minimo = 'IRPF Ahorro'[Mínimo]
			                    VAR maximo = 'IRPF Ahorro'[Máximo]
			
			                    VAR irpf = IF (minimo = 0, MIN(beneficio - minimo, maximo), MIN(MAX(BLANK(), beneficio - minimo), maximo))
			
			                    RETURN IF (irpf=0, BLANK(), irpf * 'IRPF Ahorro'[Tipo])
			            ) 
			        ) 
			```
		lineageTag: a7b08e50-4577-4087-bf7a-e4a5fd05428e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Tipo IRPF Anual Ahorro' = ```
			
			
			VAR fiscal_year = SELECTEDVALUE(Transacciones[Año IRPF])
			
			RETURN   
			    CALCULATE(
			            DIVIDE([IRPF Anual Ahorro], [Base Imponible del Ahorro])
			            , Transacciones[Año IRPF] = fiscal_year
			    )        
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d46c24e9-133e-4295-a1ad-2707722c7281

	/// Ganancia / Pérdida Patrimonial entre las fechas seleccionadas de inicio y fin de período. 
	/// 
	/// Incluye solo las ganancias / pérdidas realizadas siguiendo un protocolo FIFO.
	measure 'Ganancias / Pérdidas Patrimoniales Realizadas' = SUM(Transacciones[Ganancias / Pérdidas Patrimoniales (GPP)])
		lineageTag: 6038c3b8-9c36-4df9-96a8-6e21c0b63051

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Presentación - Tipo IRPF Anual' = COALESCE([Tipo IRPF Anual Ahorro], "Seleccione Año")
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7b3e8605-d345-4583-b489-42ef3a2b5ec9

	measure 'Rendimientos Capital Mobiliario' = SUM(Transacciones[Rendimientos Capital Mobiliario])
		lineageTag: 7052e4fd-3e0d-4afe-af01-bf158bfe263d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Base Imponible del Ahorro' = [Ganancias / Pérdidas Patrimoniales Realizadas] + [Rendimientos Capital Mobiliario]
		lineageTag: 470bc87d-6193-48ca-a4f3-cd0b941546da

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Retención Ya Efectuada' = SUM(Transacciones[Retenido])
		lineageTag: 889695e9-819b-45c1-a102-5740bb364a9a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ganancia Neta Capital Mobiliario' = [Rendimientos Capital Mobiliario] * (1 - [Tipo IRPF Anual Ahorro])
		lineageTag: bb517e35-d97c-4b3c-b58b-8f2fd2f6d42e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gastos Deducibles' = SUM(Transacciones[Comisión])
		lineageTag: 7cffd500-e201-45b6-b3ee-9096b9097ce0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gastos No Deducibles' = SUM(Transacciones[Comisión])
		lineageTag: 10a577cc-706c-452b-827f-d6a30235bb03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Medidas IRPF' = m
		mode: import
		queryGroup: IRPF
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

