table Test
	lineageTag: 21f1dadb-4d7a-4526-b93d-83e230fcb845

	measure 'Test - Medida Seleccionada' = ```
			
			
			SWITCH(
			    SELECTEDVALUE('Test Data'[Medida])
			    , "Saldo Fecha Inicio", [Saldo Fecha Inicio]
			    , "Saldo Último", [Saldo Último]
			    , "Gastos no Computados Periodo", [Gastos No Computados - Valor Periodo]
			    , "Ganancia / Pérdida Patrimonial Total", [Saldo - Ganancia / Pérdida Patrimonial]
			    , "Transacción - Ganancias / Pérdidas Patrimoniales Realizadas", [Transacción - Ganancias / Pérdidas Patrimoniales Realizadas]
			    , "Anual - Ganancias / Pérdidas Patrimoniales Realizadas", [Anual - Ganancias / Pérdidas Patrimoniales Disponibles]
			    , "Transacción - Rendimientos Capital Mobiliario", [Transacción - Rendimientos Capital Mobiliario]
			    , "Anual - Rendimientos Capital Mobiliario", [Anual - Rendimientos Capital Mobiliario]
			    , "Movimientos Totales Periodo", [Saldo - Movimientos Caja - Total Periodo]
			    , "Beneficio Bruto Total Periodo", [Transacciones - Beneficio Bruto Total Periodo]
			    , "Transacción - IRPF Anual Ahorro", [Transacción - IRPF Anual Ahorro]   
			    , "Anual - IRPF Ahorro", [Anual - IRPF Ahorro]   
			    , "Transacción - IRPF Anual Ahorro Pendiente", [Transacción - IRPF Anual Ahorro Pendiente]   
			    , "Transacción - Tipo IRPF Anual Ahorro", [Transacción - Tipo IRPF Anual Ahorro]
			    , "Anual - Tipo IRPF Ahorro", [Anual - Tipo IRPF Ahorro]
			    , "Ingresos Inversión", [Ingresos Inversion]
			    , "Transacción - Base Imponible del Ahorro", [Transacción - Base Imponible del Ahorro]
			    , "Anual - Base Imponible del Ahorro", [Anual - Base Imponible del Ahorro]
			    , "Anual - Pérdidas GPP Remanentes", [Anual - Pérdidas GPP Remanentes]
			    , "Anual - Pérdidas RCM Remanentes", [Anual - Pérdidas RCM Remanentes]
			    , "Anual - Pérdidas GPP Dsiponibles", [Anual - Pérdidas GPP Disponibles]
			    , "Anual - Pérdidas RCM Disponible", [Anual - Pérdidas RCM Disponibles]
			    , "MEDIDA NO REGISTRADA"
			)
			```
		lineageTag: fd9278ab-02ea-4140-9799-f46f3b6af606

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Test - Número Errores' = ```
			
			
			SUMX(
			    SUMMARIZE('Test Data', 'Test Data'[Medida],'Test Data'[Caso],'Test Data'[Validación]), 
			    CALCULATE(
			        [Test - Medida Seleccionada]
			        , 'Test Genérico'[Test Genérico] = "Error"
			    )
			)
			```
		formatString: 0
		lineageTag: 897aa625-ca38-44b6-9c3a-38cbf0a8d2d7

	measure 'Test - Passed Rate' = DIVIDE(COUNTROWS('Test Data') - Test[Test - Número Errores], COUNTROWS('Test Data'))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d152038e-7dfc-4454-ba5f-ab06f4376394

	measure 'Texto - Errores' = FORMAT(Test[Test - Número Errores], "#,0") & "/" & FORMAT(COUNTROWS('Test Data'),"#,0")
		lineageTag: 2cacabf8-fd7b-4fbd-a63e-2deaa18eb84a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		isHidden
		lineageTag: 4424ad8e-526d-4d32-9602-573283ca39a1
		summarizeBy: none
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition Test = calculated
		mode: import
		source = {""}

	annotation PBI_Id = 8da5445724bc4ea5aed1d160fc5f002a

