table 'Test Data'
	lineageTag: b4022ae7-63a8-4ebd-a1c0-0f326d7e47b7

	column Medida
		dataType: string
		lineageTag: ba75b998-921b-4a1e-8036-e580edf6dfb7
		summarizeBy: none
		sourceColumn: Medida

		annotation SummarizationSetBy = Automatic

	column Descripción
		dataType: string
		lineageTag: 979c04f1-b76c-4eea-b3ae-5d98e555b6a8
		summarizeBy: none
		sourceColumn: Descripción

		annotation SummarizationSetBy = Automatic

	column 'Valor Esperado'
		dataType: string
		lineageTag: 1af90a23-7bd1-40c5-949f-15dad93c6281
		summarizeBy: none
		sourceColumn: Valor Esperado

		annotation SummarizationSetBy = Automatic

	column Concepto
		dataType: string
		lineageTag: be2e9636-997e-446c-ad26-91b3d2b10524
		summarizeBy: none
		sourceColumn: Concepto

		annotation SummarizationSetBy = Automatic

	column Caso
		dataType: string
		lineageTag: 327edb81-db53-46ea-a2e4-77f2dd1d6934
		summarizeBy: none
		sourceColumn: Caso

		annotation SummarizationSetBy = Automatic

	column Validación
		dataType: int64
		formatString: 0
		lineageTag: 35f1e2b2-6e10-4b3a-b5fb-ea5441d45400
		summarizeBy: sum
		sourceColumn: Validación

		annotation SummarizationSetBy = Automatic

	column año
		dataType: int64
		formatString: 0
		lineageTag: 005432e7-0b52-4366-9b94-cc33c280ccbe
		summarizeBy: sum
		sourceColumn: año

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: int64
		formatString: 0
		lineageTag: f2c58510-ac90-4197-bed0-5a07246ab0d4
		summarizeBy: sum
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column 'año IRPF'
		dataType: int64
		formatString: 0
		lineageTag: b0685e5c-e49c-4fef-9b88-fdb86b643b7e
		summarizeBy: sum
		sourceColumn: año IRPF

		annotation SummarizationSetBy = Automatic

	partition 'Test Data' = m
		mode: import
		queryGroup: Test
		source = ```
				let
				    Origen = #"Origen Data File",    
				    T_Saldo_Table = Origen{[Item="T_TestData",Kind="Table"]}[Data],
				
				    resultado = if List.Contains(List.Transform(Origen[Name], Text.Lower), "t_testdata") then 
				
				        let        
				            #"Tipo cambiado" = Table.TransformColumnTypes(T_Saldo_Table,{{"Medida", type text}, {"Caso", type text}, {"Descripción", type text}}),
				            #"JSON analizado" = Table.TransformColumns(#"Tipo cambiado",{{"Parámetros", Json.Document}}),
				            #"Se expandió Parámetros" = Table.ExpandRecordColumn(#"JSON analizado", "Parámetros", {"año", "mes", "año IRPF"}, {"año", "mes", "año IRPF"}),
				            #"test_data" = Table.TransformColumnTypes(#"Se expandió Parámetros",{{"año", Int64.Type}, {"mes", Int64.Type}, {"año IRPF", Int64.Type}, {"Valor Esperado", type text}, {"Concepto", type text}})
				
				        in 
				            #"test_data"
				
				    else
				        #table({"Medida","Concepto", "Caso","Descripción","Valor Esperado","mes","año","año IRPF", "Validación"}, {}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(resultado,{{"Medida", type text}, {"Concepto", type text}, {"Caso", type text}, {"Descripción", type text}, {"Valor Esperado", type text}, {"Validación", Int64.Type}, {"mes", Int64.Type}, {"año", Int64.Type}, {"año IRPF", Int64.Type}})
				in
				    #"Tipo cambiado"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

