table Transacciones
	lineageTag: c1c9e7c5-0686-4cc6-aa8e-71faa3fa78dc

	column Fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: 86a616c3-5754-453e-8477-954ded922a72
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Producto
		dataType: string
		lineageTag: 80f7151b-24e8-4357-81fb-091ad039e35c
		summarizeBy: none
		sourceColumn: Producto

		annotation SummarizationSetBy = Automatic

	column 'Tipo Transacción'
		dataType: string
		lineageTag: b4a60f7c-46df-46f2-b608-15cdc53b02b7
		summarizeBy: none
		sourceColumn: Tipo Transacción

		annotation SummarizationSetBy = Automatic

	column Participaciones
		dataType: double
		lineageTag: e5ac0577-247e-44ad-a7ce-6f80512e541c
		summarizeBy: sum
		sourceColumn: Participaciones

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Retenido
		dataType: double
		lineageTag: 3b71121f-fe73-4dc0-851c-c0a3c5e68f58
		summarizeBy: sum
		sourceColumn: Retenido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Comisión
		dataType: double
		formatString: #,0\ "€";-#,0\ "€";#,0\ "€"
		lineageTag: d231549f-35c6-4457-b10f-a52470732cde
		summarizeBy: sum
		sourceColumn: Comisión

		annotation SummarizationSetBy = Automatic

	column 'Año IRPF'
		dataType: double
		formatString: 0
		lineageTag: d545caa2-fedd-438a-9519-c710c492b449
		summarizeBy: none
		sourceColumn: Año IRPF

		annotation SummarizationSetBy = Automatic

	column 'Año IRPF Fijado'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 15b59662-2885-4e33-9f2d-c38ca3b1bd78
		summarizeBy: none
		sourceColumn: Año IRPF Fijado

		annotation SummarizationSetBy = Automatic

	column 'Precio Participación'
		dataType: double
		lineageTag: 273f3931-a232-4208-8462-b8ac7216281e
		summarizeBy: sum
		sourceColumn: Precio Participación

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cambio
		dataType: double
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 8ff5e451-e1fd-49a6-8135-191d51e763bb
		summarizeBy: sum
		sourceColumn: Cambio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'Total Bruto'
		dataType: double
		lineageTag: 139098c4-e3bc-4763-8a0a-84e38a48ed63
		summarizeBy: sum
		sourceColumn: Total Bruto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Renta Bruta Obtenida'
		dataType: double
		lineageTag: 21c52de9-6690-4863-8877-72dd3a9aa319
		summarizeBy: sum
		sourceColumn: Renta Bruta Obtenida

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cuenta Producto'
		dataType: string
		lineageTag: 19ef5e5d-6dba-4baa-99ae-14492eb5c9c0
		summarizeBy: none
		sourceColumn: Cuenta Producto

		annotation SummarizationSetBy = Automatic

	column 'Producto Contraparte'
		dataType: string
		lineageTag: adab4216-f23d-4edd-8dd7-e6b5f16e2e1d
		summarizeBy: none
		sourceColumn: Producto Contraparte

		annotation SummarizationSetBy = Automatic

	column 'Cuenta Contraparte'
		dataType: string
		lineageTag: f9fb0fd3-ac88-48a5-9ac4-6313711f45fe
		summarizeBy: none
		sourceColumn: Cuenta Contraparte

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 6545e87d-9278-4379-8861-18fd40954b11
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'IRPF Calculado' = [Transacción - IRPF Anual Ahorro]
		dataType: double
		lineageTag: 52f32b40-183d-46c3-8ac8-3451be29df89
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Hora
		dataType: dateTime
		formatString: Long Time
		lineageTag: 544ae988-d1c9-4c32-b4e8-08d22ab28202
		summarizeBy: none
		sourceColumn: Hora

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Precio (Moneda Transacción)'
		dataType: double
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: a9f0d92f-9c50-4674-9bc9-bfdd9f3d8e85
		summarizeBy: sum
		sourceColumn: Precio (Moneda Transacción)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'Importe Bruto (Moneda Transacción)'
		dataType: double
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: a2596994-ca4a-49b0-a9ad-448a262d0204
		summarizeBy: sum
		sourceColumn: Importe Bruto (Moneda Transacción)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'Retenido (Moneda Transacción)'
		dataType: double
		lineageTag: ce5dbe70-d11b-4b71-9ccc-0fb392eb3f3c
		summarizeBy: sum
		sourceColumn: Retenido (Moneda Transacción)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Comisión (Moneda Transacción)'
		dataType: double
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: bc9edcbc-6ddd-4c8d-8dbf-60352407e1e4
		summarizeBy: sum
		sourceColumn: Comisión (Moneda Transacción)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Detalle
		dataType: string
		lineageTag: 0ef2e46e-de36-4a1d-bfbc-d24c91609dd4
		summarizeBy: none
		sourceColumn: Detalle

		annotation SummarizationSetBy = Automatic

	column Test
		dataType: string
		isHidden
		lineageTag: c6b0f786-3c31-4f6a-98a1-c3d7bc195c39
		summarizeBy: none
		sourceColumn: Test

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Importe
		dataType: double
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 02d2c9c9-75e0-467b-85ae-54ee93c0a558
		summarizeBy: sum
		sourceColumn: Importe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column 'Participaciones Acumuladas'
		dataType: double
		formatString: 0
		lineageTag: 63d16587-c18e-46be-904e-52fb9df4dc27
		summarizeBy: sum
		sourceColumn: Participaciones Acumuladas

		annotation SummarizationSetBy = Automatic

	column 'Precio Medio Hasta Transacción'
		dataType: double
		formatString: 0
		lineageTag: 3b1a9f36-8eeb-40e1-9e58-b0aba44241d6
		summarizeBy: sum
		sourceColumn: Precio Medio Hasta Transacción

		annotation SummarizationSetBy = Automatic

	column 'FIFO Beneficio / Pérdida'
		dataType: double
		formatString: #,0.0000\ "€";-#,0.0000\ "€";#,0.0000\ "€"
		lineageTag: c8671f87-ca1d-40a1-9fd3-17db2689b499
		summarizeBy: sum
		sourceColumn: FIFO Beneficio / Pérdida

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Fecha/Hora
		dataType: dateTime
		formatString: General Date
		lineageTag: 465e905f-fe58-426e-9bac-9a7cb85eae28
		summarizeBy: none
		sourceColumn: Fecha/Hora

		variation Variación
			isDefault
			relationship: b40c6ee6-4ff4-4108-9c87-8c3405be1394
			defaultHierarchy: LocalDateTable_93f1543f-944f-4988-9370-48e3eab51efc.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Divisa
		dataType: string
		lineageTag: 78626fdc-a244-4a5f-839c-6a3c8783a3fc
		summarizeBy: none
		sourceColumn: Divisa

		annotation SummarizationSetBy = Automatic

	column 'Rendimientos Capital Mobiliario'
		dataType: double
		lineageTag: 7f606251-7b39-46bc-8264-f04216e32fc8
		summarizeBy: sum
		sourceColumn: Rendimientos Capital Mobiliario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gastos No Deducibles'
		dataType: double
		lineageTag: 253d1294-463d-4a1d-9252-af1c2066c578
		summarizeBy: sum
		sourceColumn: Gastos No Deducibles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Gastos Deducibles'
		dataType: double
		lineageTag: 69284492-feea-499e-893b-56ef18a6a1fe
		summarizeBy: sum
		sourceColumn: Gastos Deducibles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Retención Local'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cc2affd5-462c-494d-bdc6-e1b0c75a9877
		summarizeBy: none
		sourceColumn: Retención Local

		annotation SummarizationSetBy = Automatic

	column _FifoAvailableShares
		dataType: string
		lineageTag: 659ae6fc-71b8-4d81-84a8-dad847ea5064
		summarizeBy: none
		sourceColumn: _FifoAvailableShares

		annotation SummarizationSetBy = Automatic

	column _FifoCostPerShareWithCommission
		dataType: string
		lineageTag: 68150635-57f3-4838-a99e-f642e2613026
		summarizeBy: none
		sourceColumn: _FifoCostPerShareWithCommission

		annotation SummarizationSetBy = Automatic

	column 'GPP - Ajuste por Pérdida Diferida'
		dataType: double
		lineageTag: cf052535-af5c-43e4-9490-024a99438b09
		summarizeBy: sum
		sourceColumn: GPP - Ajuste por Pérdida Diferida

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'País Retención'
		dataType: string
		lineageTag: 8092bce9-66cb-48fd-b178-90f23ef43ce9
		summarizeBy: none
		sourceColumn: País Retención

		annotation SummarizationSetBy = Automatic

	column 'Ganancias / Pérdidas Patrimoniales Disponibles (GPP)'
		dataType: double
		lineageTag: 7b1220f3-52eb-481c-a75d-730bc25bd964
		summarizeBy: sum
		sourceColumn: Ganancias / Pérdidas Patrimoniales Disponibles (GPP)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'GPP Total'
		dataType: double
		lineageTag: 3af9c878-586d-4396-b900-662266385cbd
		summarizeBy: sum
		sourceColumn: GPP Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Cambio Fijo'
		dataType: string
		lineageTag: c12b5589-3c63-4240-bc23-7039fd8b415c
		summarizeBy: none
		sourceColumn: Cambio Fijo

		annotation SummarizationSetBy = Automatic

	column 'País Retención2'
		dataType: string
		lineageTag: 5c812cc2-613f-4308-9452-0275985fece4
		summarizeBy: none
		sourceColumn: País Retención2

		annotation SummarizationSetBy = Automatic

	column 'PyG realizadas'
		dataType: string
		lineageTag: f22a0f5e-3001-4557-b84f-7fd1736abfd5
		summarizeBy: none
		sourceColumn: PyG realizadas

		annotation SummarizationSetBy = Automatic

	column 'ID Divisa'
		dataType: string
		lineageTag: 8da5b92e-4da5-44db-b1cb-3856b2ec4033
		summarizeBy: none
		sourceColumn: ID Divisa

		annotation SummarizationSetBy = Automatic

	column 'ID Transacción'
		dataType: string
		lineageTag: 0bee44f0-c2f6-44df-8ffb-4db8f0c87d00
		summarizeBy: none
		sourceColumn: ID Transacción

		annotation SummarizationSetBy = Automatic

	column 'Check No contempladas'
		dataType: string
		lineageTag: 41ca4fcb-516a-45b5-b40b-2409a38debaf
		summarizeBy: none
		sourceColumn: Check No contempladas

		annotation SummarizationSetBy = Automatic

	column 'Transacciones Preclasificadas.Comisión (Moneda Transacción)'
		dataType: string
		lineageTag: 655fb543-43de-484c-9a31-f7f24056de3b
		summarizeBy: none
		sourceColumn: Transacciones Preclasificadas.Comisión (Moneda Transacción)

		annotation SummarizationSetBy = Automatic

	partition Transacciones = m
		mode: import
		queryGroup: Saldo
		source = ```
				let    
				    Origen = #"Transacciones Power Query",
				    #"Filas ordenadas" = Table.Sort(Origen,{{"Fecha", Order.Ascending}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Filas ordenadas",{{"Fecha", type text}, {"Hora", type text}}),
				    #"[Buffer]" = Table.Buffer(#"Tipo cambiado"),
				//    #"[Python] Execute" = Python.Execute("import pyportfolio.scripts.powerquery.pq_get_fifo_irpf_data as script#(lf)#(lf)import logging#(lf)#(lf)logger = logging.getLogger(__name__)#(lf)#(lf)logging.basicConfig(filename='G:\Mi unidad\logfile.log', level=logging.DEBUG, # Changed to INFO for more detail#(lf)                    format='%(asctime)s - %(name)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s')#(lf)#(lf)result = script.pq_get_fifo_irpf_data(dataset)#(lf)#(lf)logger.debug(f""Power Query Actual columns: {result.columns.tolist()}"")#(lf)#(lf)result",[dataset=#"[Buffer]"]),
				    #"[Python] Execute" = Python.Execute("import pyportfolio.scripts.powerquery.pq_get_fifo_irpf_data as script#(lf)#(lf)import logging#(lf)#(lf)logger = logging.getLogger(__name__)#(lf)#(lf)logging.basicConfig(filename='C:\\Users\\Public\\Log\\logfile.log', level=logging.INFO, #(lf)                   format='%(asctime)s - %(name)s - %(module)s - %(funcName)s - %(levelname)s - %(message)s')#(lf)#(lf)result = script.pq_get_fifo_irpf_data(dataset)#(lf)#(lf)logger.debug(f""Power Query Actual columns: {result.columns.tolist()}"")#(lf)#(lf)result",[dataset=#"[Buffer]"]),
				    #"[Python] Result" = #"[Python] Execute"{[Name="result"]}[Value],
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"[Python] Result",{{"GPP Allowable", "Ganancias / Pérdidas Patrimoniales Disponibles (GPP)"}, {"GPP - Deferred Loss Adjustment", "GPP - Ajuste por Pérdida Diferida"}}),
				    #"[Update] Subst - . by ," = Table.TransformColumns(
				        #"Columnas con nombre cambiado", 
				        {{"Participaciones", each Text.Replace(_, ".", ",")},
				        {"Precio Participación", each Text.Replace(_, ".", ",")},
				        {"Precio (Moneda Transacción)", each Text.Replace(_, ".", ",")},
				        {"Cambio", each Text.Replace(_, ".", ",")},
				        {"Importe", each Text.Replace(_, ".", ",")},
				        {"Importe Bruto (Moneda Transacción)", each Text.Replace(_, ".", ",")},
				        {"Retenido", each Text.Replace(_, ".", ",")}, 
				        {"Retenido (Moneda Transacción)", each Text.Replace(_, ".", ",")},
				        {"Comisión", each Text.Replace(_, ".", ",")},
				        {"Comisión (Moneda Transacción)", each Text.Replace(_, ".", ",")},
				        {"Total Bruto", each Text.Replace(_, ".", ",")}, 
				        {"Participaciones Acumuladas", each Text.Replace(_, ".", ",")},
				        {"Precio Medio Hasta Transacción", each Text.Replace(_, ".", ",")}, 
				        {"Renta Bruta Obtenida", each Text.Replace(_, ".", ",")},
				        {"FIFO Beneficio / Pérdida", each Text.Replace(_, ".", ",")},
				        {"Ganancias / Pérdidas Patrimoniales Disponibles (GPP)", each Text.Replace(_, ".", ",")},
				        {"GPP - Ajuste por Pérdida Diferida", each Text.Replace(_, ".", ",")},
				        {"GPP Total", each Text.Replace(_, ".", ",")},
				        {"Rendimientos Capital Mobiliario", each Text.Replace(_, ".", ",")},
				        {"Año IRPF", each Text.Replace(_, ".", ",")}}
				    ),
				
				    #"[Column][Add] Gastos No Deducibles" = Table.AddColumn(#"[Update] Subst - . by ,", "Gastos No Deducibles", each if [Tipo Transacción] = "Dividendos" then [Comisión] else 0),
				    #"[Column][Add] Gastos Deducibles" = Table.AddColumn(#"[Column][Add] Gastos No Deducibles", "Gastos Deducibles", each if [Tipo Transacción] <> "Dividendos" then [Comisión] else 0),
				    #"Columna condicional agregada" = Table.AddColumn(#"[Column][Add] Gastos Deducibles", "Retención Local", each if [País Retención] = "" or [País Retención] = "ESP" then true else false, type logical),
				    #"[Update] Types" = Table.TransformColumnTypes(#"Columna condicional agregada",{{"Fecha", type date}, {"Producto", type text}, {"Cuenta Producto", type text}, {"Hora", type time}, {"Producto Contraparte", type text}, {"Cuenta Contraparte", type text}, {"Tipo Transacción", type text}, {"Participaciones", type number}, {"Precio Participación", type number}, {"Precio (Moneda Transacción)", type number}, {"Divisa", type text}, {"Cambio", type number}, {"Importe", type number}, {"Importe Bruto (Moneda Transacción)", type number}, {"Retenido", type number}, {"Retenido (Moneda Transacción)", type number}, {"Año IRPF", type number}, {"Comisión", type number}, {"Comisión (Moneda Transacción)", type number}, {"Detalle", type text}, {"Test", type text}, {"Fecha/Hora", type datetime}, {"Total Bruto", type number}, {"Año IRPF Fijado", type logical}, {"ID", Int64.Type}, {"Participaciones Acumuladas", type number}, {"Precio Medio Hasta Transacción", type number}, {"Renta Bruta Obtenida", type number}, {"FIFO Beneficio / Pérdida", type number}, {"Rendimientos Capital Mobiliario", type number}, {"Ganancias / Pérdidas Patrimoniales Disponibles (GPP)", type number}, {"GPP Total", type number}, {"GPP - Ajuste por Pérdida Diferida", type number}, {"Gastos No Deducibles", type number}, {"Gastos Deducibles", type number}})
				in
				    #"[Update] Types"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

